"""English content. Prices via [[key]] (see siteconf.py)."""

UI = {
    "skip": "Skip to content",
    "menu": "Menu", "close": "Close",
    "nav_services": "Services", "nav_pricing": "Pricing", "nav_method": "How we work",
    "nav_work": "Work", "nav_about": "About", "nav_contact": "Contact",
    "cta_scan": "Free growth scan", "whatsapp": "WhatsApp", "whatsapp_long": "Send a WhatsApp",
    "from": "from", "per_month": "/month", "per_month_long": "per month", "excl": "excl. VAT",
    "free": "free", "on_quote": "on quote", "more": "Learn more", "home": "Home",
    "packages_h": "Packages and prices", "steps_h": "How it works", "faq_h": "Frequently asked questions",
    "related_h": "You might also like", "all_services": "All services", "all_prices": "All prices",
    "footer_services": "Services", "footer_company": "Rozmary", "footer_contact": "Contact",
    "footer_area": "Where we work", "footer_tagline": "Digital partner for start-ups and small businesses.",
    "kbo": "Company number", "kbo_missing": "Company number to follow", "privacy": "Privacy",
    "rights": "All prices excl. VAT.", "lang_label": "Language",
    "cta_band_h": "Curious where your business is losing customers?",
    "cta_band_p": "Ask for a free growth scan. We review your website, Google profile, reviews and three competitors, and talk it through in 15 minutes.",
    "breadcrumb": "Breadcrumb",
    "wa_general": "Hi Rozmary Digital, I have a question.",
    "wa_service": "Hi Rozmary Digital, I have a question about {s}.",
    "region": "Kempen region", "recommended": "Recommended",
    "form": {
        "name": "Name", "company": "Company (optional)", "email": "Email",
        "phone": "Phone (optional)", "website": "Website (if you have one)",
        "city": "Town", "interest": "How can we help?", "other": "Something else",
        "message": "Your message", "consent": "Rozmary Digital may use my details to contact me.",
        "consent_link": "Privacy", "submit": "Send", "sending": "Sending…",
        "ok": "Thank you! We reply within one working day.",
        "fail": "Sending failed. Send your message via WhatsApp or email us.",
        "wa_fallback": "Send via WhatsApp", "required": "Required",
        "wa_intro": "Hi Rozmary Digital, ",
    },
}

STEPS = [
    ("Introduction", "In 15 minutes we talk about your business, your goal and your budget."),
    ("Fixed-price proposal", "You get a clear proposal. Happy with it? You pay a 50% deposit."),
    ("We build, you approve", "You follow along and get two rounds of changes."),
    ("Live and follow-up", "We launch, measure the results and suggest a monthly plan if it makes sense."),
]

SERVICES = {
    "website": {
        "nav": "Website",
        "title": "Website design from €995 | Rozmary Digital",
        "desc": "Website design for start-ups and small businesses in Belgium: one-page site from €995, business site from €2,495. Copy, local SEO and WhatsApp button included.",
        "h1": "Website design from [[web_start]]",
        "lead": "A fast website that people find and that turns visitors into enquiries. Copy, local SEO, a WhatsApp button and tracking are included.",
        "chips": ["Live in 7 working days", "Copy included", "Domain in your name"],
        "card": "Fast, findable site with copy and a WhatsApp button.",
        "price_card": "[[web_start]]",
        "intro_h": "A website that works for you",
        "intro": "Most small businesses don't need a prettier website. They need one that gets found and brings in enquiries. So we build every site around what your customers search for, with one clear action.",
        "bullets": [
            "Copy based on what your customers actually search for",
            "A page per service and per town, if you want",
            "WhatsApp, call and quote buttons on every page",
            "Tracking of calls, messages and enquiries",
            "Technically sound: fast, mobile-friendly, secure and with correct Google data",
        ],
        "packages": [
            {"name": "Website Start", "price": "[[web_start]]", "items": ["One-page site with up to 6 sections", "Copy and keywords included", "WhatsApp, call and quote buttons", "Basic Google setup and tracking", "Live in 7 working days"], "cta": "Start my website"},
            {"name": "Website Growth", "price": "[[web_grow]]", "featured": True, "items": ["8 to 15 pages", "A page per service and per town", "Two languages of your choice", "Blog or news section", "Pricing and FAQ page"], "cta": "Request a proposal"},
            {"name": "Starter Package", "price": "[[starter]]", "note": "or [[starter_m]] per month", "items": ["Website Start", "Logo and brand identity", "250 business cards", "Google profile set up"], "cta": "See the package", "link": "starter"},
        ],
        "packages_note": "Hosting and maintenance: Carefree for [[care]] per month. All prices excl. VAT.",
        "faq": [
            ("How much does a website cost?", "With us, [[web_start]] for a one-page site and [[web_grow]] for a site with 8 to 15 pages, excl. VAT. In Belgium, prices range from €550 with a freelancer to €7,000 or more with larger agencies."),
            ("Can I pay for a website monthly?", "Yes. With the Starter Package you pay [[starter_m]] per month for 24 months, with no deposit. Hosting and maintenance are included."),
            ("Can ChatGPT build a website?", "It can produce a rough version. What's missing is the rest: keyword research, fast hosting, correct Google data, tracking and someone to maintain your site. That's what we do, and we use AI to make it faster and more affordable."),
            ("Who owns the website when it's finished?", "You do. The domain is registered in your name and you get all the files. If you stop our maintenance, we help you move."),
        ],
        "related": ["starter", "google", "brand"],
    },
    "starter": {
        "nav": "Starter Package",
        "title": "Starter package for new businesses: €1,495 | Rozmary",
        "desc": "Just started your business? Logo, brand identity, 250 business cards, website and Google profile in one package: €1,495, or €99 a month with no deposit.",
        "h1": "Starter Package: everything to get started for [[starter]]",
        "lead": "Logo, brand identity, business cards, website and Google profile in one go. You can also pay monthly, with no deposit.",
        "chips": ["Or [[starter_m]] per month", "Ready in 3 weeks", "One point of contact"],
        "card": "Logo, business cards, website and Google profile in one package.",
        "price_card": "[[starter]]",
        "intro_h": "Get your first impression right",
        "intro": "When you're starting out, you already have enough on your plate. With the Starter Package your business looks professional online and on paper in one go, without juggling five suppliers.",
        "bullets": [
            "Logo and brand identity: colours, fonts and a mini brand guide",
            "250 printed business cards, delivered to your door",
            "Website Start: a one-page site with copy and a WhatsApp button",
            "Google profile set up, with a review link and QR cards",
            "When paying monthly: hosting and maintenance included",
        ],
        "packages": [
            {"name": "One payment", "price": "[[starter]]", "featured": True, "items": ["Logo and brand identity", "250 business cards", "Website Start", "Google Profile Boost"], "cta": "Choose the package"},
            {"name": "Monthly", "price": "[[starter_m]]", "per": True, "items": ["The same package, no deposit", "Hosting and maintenance included", "24 months, then Carefree at [[care]] per month", "Domain in your name"], "cta": "Pay monthly"},
        ],
        "packages_note": "Bought separately, this adds up to [[starter_loose]]. All prices excl. VAT.",
        "steps": [
            ("Introduction", "In 15 minutes we talk about your business, your customers and your style."),
            ("Brand identity (week 1)", "You get three logo concepts and two rounds of changes."),
            ("Website and print (week 2)", "We build your site and order your business cards."),
            ("Live and findable (week 3)", "Your site goes live and your Google profile is ready for your first reviews."),
        ],
        "faq": [
            ("What exactly is in the Starter Package?", "A logo with brand identity and mini brand guide, 250 printed business cards, a one-page website with copy and a WhatsApp button, and a fully set-up Google profile with a review link and QR cards."),
            ("Can I pay for the package monthly?", "Yes, [[starter_m]] per month for 24 months, with no deposit. Hosting and maintenance are included."),
            ("I already have a logo. Can you adjust the package?", "Of course. We swap the brand identity for something you do need, such as extra pages or print."),
            ("How long does it take?", "Three weeks on average, depending on how quickly you give feedback."),
        ],
        "related": ["website", "brand", "cards"],
    },
    "brand": {
        "nav": "Logo & branding",
        "title": "Logo design from €249 | Brand identity | Rozmary",
        "desc": "Logo design or a complete brand identity: logo from €249, brand identity with business card and social media templates for €595. Fixed price, all files.",
        "h1": "Logo and brand identity design, from [[logo]]",
        "lead": "A recognisable logo and a brand that looks the same everywhere: on your shopfront, your website, your van and Instagram.",
        "chips": ["3 concepts", "2 rounds of changes", "All files"],
        "card": "A recognisable logo and a brand that fits everywhere.",
        "price_card": "[[logo]]",
        "intro_h": "More than a logo",
        "intro": "These days you can make a logo in five minutes with an app. A brand identity that speaks to your customers and works at every size is something else. We build it with you.",
        "bullets": [
            "Logo in colour, black and white, and as an icon",
            "Colour palette and fonts",
            "Business card and email signature",
            "Templates for Instagram and Facebook",
            "A mini brand guide so everyone uses your style correctly",
        ],
        "packages": [
            {"name": "Logo Start", "price": "[[logo]]", "items": ["3 logo concepts", "2 rounds of changes", "Files for web and print (SVG, PNG, PDF)"], "cta": "Order Logo Start"},
            {"name": "Brand identity", "price": "[[brand]]", "featured": True, "items": ["Everything in Logo Start", "Colours and fonts", "Business card design", "Social media templates", "Mini brand guide"], "cta": "Start my brand"},
        ],
        "packages_note": "All prices excl. VAT. After payment, all rights are yours.",
        "faq": [
            ("How much does a logo cost?", "With us, [[logo]] for Logo Start and [[brand]] for a complete brand identity, excl. VAT. Online you'll see prices from €99 to €279 for just a logo."),
            ("Can ChatGPT make a logo?", "AI tools quickly produce an image, but often without a unique character, without usable files and without clarity about the rights. We use AI for quick sketches and then design the logo ourselves."),
            ("Where can I make a logo for free?", "With tools like Canva, and for a first test that's fine. If you want a logo that stays sharp at every size and suits your customers, a custom design pays off."),
            ("Who owns the rights?", "After payment, all rights to the logo and brand identity are yours."),
        ],
        "related": ["cards", "starter", "social"],
    },
    "cards": {
        "nav": "Business cards",
        "title": "Business cards: design and printing for €119 | Rozmary",
        "desc": "Business cards designed and printed for you: 250 cards in your brand style for €119, delivered to your door. Or a digital business card with a QR code for €79.",
        "h1": "Business cards: design and printing for [[cards]]",
        "lead": "You don't design or order anything yourself. We create the design in your brand style, then have 250 cards printed and delivered.",
        "chips": ["250 cards included", "Delivered to your door", "Digital option"],
        "card": "Design and printing of 250 cards, or a digital card.",
        "price_card": "[[cards]]",
        "intro_h": "Cards that fit your business",
        "intro": "An online printer is cheap, but then you design it yourself. We make sure your card matches your logo, your website and your shopfront, with every detail in the right place.",
        "bullets": [
            "Double-sided design in your brand style",
            "Every detail checked and a print-ready file",
            "250 cards on sturdy paper, delivered to your door",
            "Extra: a digital business card with a QR code",
        ],
        "packages": [
            {"name": "Business Cards Start", "price": "[[cards]]", "featured": True, "items": ["Design in your brand style", "250 printed cards", "Delivery in Belgium"], "cta": "Order your cards"},
            {"name": "Digital business card", "price": "[[vcard]]", "note": "+ [[vcard_m]] per month", "items": ["Your own contact page", "QR code for your card or shopfront", "Button to save your contact", "Changes included"], "cta": "Order digital"},
        ],
        "packages_note": "All prices excl. VAT.",
        "faq": [
            ("Can I order just the design?", "Yes, then you get a print-ready file. Ask via WhatsApp or the contact form."),
            ("How long does it take?", "Once you approve the design, your cards usually arrive within a week."),
            ("What is a digital business card?", "A web page with your details, buttons to call or email you and a button to save your contact. With a QR code you share it in a second."),
            ("I don't have a logo yet. What now?", "Then start with Logo Start or the Starter Package, which already includes 250 cards."),
        ],
        "related": ["brand", "starter", "google"],
    },
    "google": {
        "nav": "Google profile",
        "title": "Google Business Profile optimisation: €149 | Rozmary",
        "desc": "Rank higher on Google Maps in your own town: we fully set up your Google Business Profile for €149, with a review link and QR cards.",
        "h1": "Google Business Profile optimisation for [[gbp]]",
        "lead": "When people search in your town, they first see the map with three businesses. We make sure you're one of them, with photos, services and reviews that convince.",
        "chips": ["Profile fully set up", "Review link and QR cards", "Local keywords"],
        "card": "Get found on Google Maps, with more reviews.",
        "price_card": "[[gbp]]",
        "intro_h": "The map wins the click",
        "intro": "For a search like ‘hairdresser Geel’, three businesses appear on the map, above all other results. Reviews, completeness and activity decide who gets there. That's exactly what we handle for you.",
        "bullets": [
            "Categories, services, opening hours and service area set correctly",
            "Ten photos and a description with your keywords",
            "Your own review link plus 50 QR cards",
            "Linked to your website, with click tracking",
            "Tips to stay visible every week",
        ],
        "packages": [
            {"name": "Google Profile Boost", "price": "[[gbp]]", "featured": True, "items": ["Profile fully set up", "Review link and 50 QR cards", "Local keywords in your description"], "cta": "Boost my profile"},
            {"name": "Local Growth Plan", "price": "[[plan_local]]", "per": True, "items": ["Two posts a week on your profile", "Review campaign via WhatsApp and email", "One new SEO page per month", "Hosting, maintenance and monthly report"], "cta": "Start the plan"},
        ],
        "packages_note": "All prices excl. VAT. Monthly plans: minimum 3 months, then cancel monthly.",
        "faq": [
            ("How do I rank higher on Google Maps?", "With a complete profile, the right category, regular updates and above all many recent, genuine reviews. In the Kempen region, the top 3 in many sectors has fewer than 50 reviews, so it's achievable."),
            ("Do you write reviews for me?", "No. Fake reviews are banned and they hurt you. We do make it very easy for your customers to leave one."),
            ("I don't have a shop. Can I still have a profile?", "Yes. If you visit your customers, you set a service area and hide your address."),
            ("I already have a profile. What do you do?", "We take it over, fill in what's missing and fix any errors."),
        ],
        "related": ["website", "ads", "social"],
    },
    "shop": {
        "nav": "Webshop",
        "title": "Webshop development from €2,995 | Rozmary Digital",
        "desc": "Webshop development with Shopify: from €2,995 for 25 products, with Bancontact and the 2026 legal requirements covered. Or start with a €149 legal check.",
        "h1": "Webshop development from [[shop]]",
        "lead": "A Shopify webshop you manage yourself, with Bancontact, shipping and the new 2026 legal requirements in order.",
        "chips": ["Shopify", "Bancontact and card", "Legally compliant"],
        "card": "Shopify webshop with Bancontact, ready for the 2026 rules.",
        "price_card": "[[shopcheck]]",
        "intro_h": "Selling without headaches",
        "intro": "A webshop is more than putting products online. Payments, shipping, returns and rules all have to be right. Since June 2026, for example, every webshop must show a clear withdrawal button.",
        "bullets": [
            "Shopify shop in your brand style",
            "25 products added, with photos and copy",
            "Payment by Bancontact and card",
            "Shipping zones, VAT and returns set up",
            "Withdrawal button, warranty information and terms that meet the 2026 rules",
        ],
        "packages": [
            {"name": "Webshop legal check", "price": "[[shopcheck]]", "items": ["Withdrawal button and form", "Warranty information and green claims", "Cookies, privacy and terms", "Prioritised action list"], "cta": "Check my webshop"},
            {"name": "Webshop Start", "price": "[[shop]]", "from": True, "featured": True, "items": ["Shopify shop in your brand style", "25 products added", "Bancontact, shipping and VAT set up", "Legal check included", "One-hour training"], "cta": "Request a proposal"},
        ],
        "packages_note": "You pay the Shopify subscription directly to Shopify. All prices excl. VAT.",
        "faq": [
            ("How much does a webshop cost?", "With us, from [[shop]] excl. VAT for a Shopify shop with 25 products. In Belgium, prices range from €1,250 to €25,000 or more, depending on custom work and integrations. On top of that you pay Shopify, from about €24 per month."),
            ("Why Shopify?", "It's reliable and secure, and you manage it yourself without technical knowledge. For large catalogues or special integrations we build custom solutions."),
            ("Which rules apply to webshops in 2026?", "Since 19 June 2026 you need a clear withdrawal button, and since 27 September 2026 new rules apply to warranty information and green claims. Our legal check lists everything for you."),
            ("Can you connect my supplier?", "Yes. For Thunder Racing we're building a connection with a supplier's catalogue, with automatic prices and stock."),
        ],
        "related": ["ads", "photo", "software"],
    },
    "ads": {
        "nav": "Advertising & funnels",
        "title": "Google Ads and Meta advertising management | Rozmary",
        "desc": "Ads on Google, Facebook and Instagram with a sales funnel that brings in enquiries. Management from €199 per month plus budget. Start with a free check.",
        "h1": "Online advertising and sales funnels",
        "lead": "Ads on Google, Facebook and Instagram, linked to a landing page and automatic follow-up. Every month you see what they bring in.",
        "chips": ["Management from [[ads_m]] per month", "Budget separate and transparent", "Monthly report"],
        "card": "Ads with a funnel that brings in enquiries.",
        "price_card": "[[ads_m]]", "price_card_per": True,
        "intro_h": "A click isn't a customer yet",
        "intro": "Clicks are expensive: in Belgium a click on ‘website laten maken’ easily costs €13. So we only advertise once the landing page is ready to convert, and we follow up every enquiry automatically.",
        "bullets": [
            "Campaigns on Google Search, Google Maps, Facebook and Instagram",
            "A landing page per campaign, with one clear action",
            "Automatic follow-up by email or WhatsApp",
            "Tracking of enquiries, not just clicks",
            "A monthly report in plain language",
        ],
        "packages": [
            {"name": "Ad check", "price": "[[scan]]", "items": ["We review your campaigns or your plan", "Three concrete improvements", "15-minute call"], "cta": "Request the check"},
            {"name": "Ad management", "price": "[[ads_m]]", "per": True, "featured": True, "items": ["Campaign setup: [[ads_setup]] one-off", "Management and optimisation", "Sales funnel with follow-up emails", "Monthly report", "Minimum 3 months"], "cta": "Start advertising"},
        ],
        "packages_note": "You pay your ad budget directly to Google or Meta. All prices excl. VAT.",
        "faq": [
            ("How much budget do I need?", "For local campaigns we recommend at least €300 per month. Less is possible, but reliable results take longer."),
            ("What is a sales funnel?", "The path from first click to customer: ad, landing page, enquiry and follow-up. We build and measure every step."),
            ("Do you promise more revenue?", "No. Nobody can honestly promise that. We do promise that every month you see what your ads bring in and what we adjust."),
            ("Why not just boost posts on Facebook?", "Boosting mostly brings likes. A campaign with a goal, an audience and tracking brings enquiries."),
        ],
        "related": ["website", "social", "google"],
    },
    "social": {
        "nav": "Social media",
        "title": "Social media management from €349 a month | Rozmary",
        "desc": "Outsource your social media: eight posts a month for Instagram and Facebook in your brand style, with planning and a report, for €349 per month.",
        "h1": "Social media management from [[social_m]] per month",
        "lead": "Eight well-planned posts a month for Instagram and Facebook, in your brand style and scheduled. You approve, we do the rest.",
        "chips": ["8 posts a month", "You approve", "Monthly report"],
        "card": "Eight posts a month in your brand style, scheduled.",
        "price_card": "[[social_m]]", "price_card_per": True,
        "intro_h": "Stay visible, without the stress",
        "intro": "Social media works when you post regularly and give your customers something useful. That rarely fits next to your actual work. We make a monthly plan, write the posts and schedule them.",
        "bullets": [
            "Monthly plan matched to your season and promotions",
            "Eight posts with copy and visuals in your brand style",
            "Scheduling on Instagram and Facebook",
            "Monthly report with reach and messages",
            "Photo or video shoot with our partner, if you like",
        ],
        "packages": [
            {"name": "Social media", "price": "[[social_m]]", "per": True, "featured": True, "items": ["8 posts a month", "Planning and scheduling", "Monthly report", "Minimum 3 months"], "cta": "Start with social media"},
            {"name": "Growth Plan Plus", "price": "[[plan_plus]]", "per": True, "items": ["Social media included", "Ad management (budget separate)", "Two SEO pages per month", "Quarterly review"], "cta": "See Growth Plan Plus", "link": "pricing"},
        ],
        "packages_note": "All prices excl. VAT.",
        "faq": [
            ("Which channels do you cover?", "Instagram and Facebook as standard. LinkedIn or TikTok on request."),
            ("Do I need to supply my own photos?", "Ideally yes, real photos work best. If you don't have any, we plan a shoot with our partner photographer."),
            ("Why not post every day?", "Two good posts a week do more than seven rushed ones. Quality and consistency win."),
            ("Is my Facebook page enough as a website?", "Better not. In 2026 UNIZO reported a wave of blocked Meta accounts. Your own website is a foundation nobody can take away."),
        ],
        "related": ["photo", "ads", "brand"],
    },
    "chatbot": {
        "nav": "AI chatbot",
        "title": "AI chatbot for your website: €495 + €39/month | Rozmary",
        "desc": "An AI chatbot that answers questions day and night based on your own content and prices, and forwards enquiries to you. €495 setup and €39 per month.",
        "h1": "An AI chatbot that helps your customers day and night",
        "lead": "Trained on your own content, prices and FAQ. It answers questions, collects enquiries and forwards them to you.",
        "chips": ["[[bot]] setup", "[[bot_m]] per month", "Says it's an AI"],
        "card": "Answers questions 24/7 based on your own information.",
        "price_card": "[[bot]]",
        "intro_h": "Fewer repeat questions, more enquiries",
        "intro": "Opening hours, prices, delivery times: many questions come back every week. A chatbot answers them straight away, even in the evening, and passes the tricky ones on to you.",
        "bullets": [
            "Answers based on your own website and documents",
            "Forwards to WhatsApp, email or your calendar",
            "Works in English, Dutch and French",
            "Always says it's an AI assistant, as the AI Act requires",
            "Monthly overview of the questions asked",
        ],
        "packages": [
            {"name": "AI chatbot", "price": "[[bot]]", "note": "+ [[bot_m]] per month", "featured": True, "items": ["Setup on your own content and FAQ", "Forwarding to WhatsApp or email", "Trilingual", "Hosting, updates and monthly overview"], "cta": "Request a demo"},
        ],
        "packages_note": "All prices excl. VAT.",
        "faq": [
            ("Is a chatbot legally compliant?", "Yes, as long as it says it's an AI. That has been mandatory under the European AI Act since 2 August 2026, and our chatbots do it by default."),
            ("What if the bot can't answer a question?", "It says so honestly and asks for your customer's contact details, so you can follow up."),
            ("What data does the bot use?", "Only what you provide: your website, prices and FAQ. Conversations are stored according to your privacy policy."),
            ("Can the bot book appointments?", "Yes, with a connection to your online calendar."),
        ],
        "related": ["software", "website", "pos"],
    },
    "photo": {
        "nav": "Photo & video",
        "title": "Business photography and video from €395 | Rozmary",
        "desc": "Business photos and videos with our partner photographers in the Kempen region: half-day shoot from €395. We plan it, you get images for web and social.",
        "h1": "Business photos and video from [[photo]]",
        "lead": "Real images of you, your team and your work. We plan the shoot with a partner photographer and put the images to work on your site and social media straight away.",
        "chips": ["Half day from [[photo]]", "Partners in the Kempen region", "Ready for web and social"],
        "card": "Real images of you and your work, through our partners.",
        "price_card": "[[photo]]",
        "intro_h": "Real photos sell better",
        "intro": "Everyone recognises a stock photo. Images of you, your team and your work build trust. We arrange the shoot and make sure the photos match your brand and your website.",
        "bullets": [
            "Shot list based on your website and social media",
            "Half-day photo shoot on location",
            "Edited photos for web and print",
            "Short videos for Instagram and Facebook, on quote",
            "Images added to your site straight away",
        ],
        "packages": [
            {"name": "Half-day photo shoot", "price": "[[photo]]", "featured": True, "items": ["Preparation and shot list", "Half day on location", "Edited photos for web and print"], "cta": "Plan a shoot"},
            {"name": "Business video", "price": None, "items": ["Short videos for social media", "Or a company film for your site", "Editing and subtitles"], "cta": "Request a quote"},
        ],
        "packages_note": "All prices excl. VAT.",
        "faq": [
            ("Who takes the photos?", "A regular partner photographer from the region. We handle the preparation and keep an eye on the result."),
            ("Can I use the photos everywhere?", "Yes, for your own communication: website, social media, print and advertising."),
            ("Can the shoot happen outside opening hours?", "Yes, by arrangement. For restaurants and shops we often plan before or after opening hours."),
        ],
        "related": ["social", "website", "brand"],
    },
    "pos": {
        "nav": "POS, CRM & invoicing",
        "title": "POS system, CRM and Peppol e-invoicing | Rozmary",
        "desc": "Peppol e-invoicing is mandatory in Belgium since 2026. We set up your invoicing software (from €149), CRM (from €395) or POS system (from €295).",
        "h1": "POS, CRM and invoicing: your admin, digital",
        "lead": "Since 1 January 2026, e-invoices via Peppol are mandatory between Belgian businesses. We choose the right tools with you and set them up, linked to your website.",
        "chips": ["Peppol-ready", "Independent advice", "Linked to your site"],
        "card": "Peppol invoicing, CRM and POS system, set up properly.",
        "price_card": "[[peppol]]",
        "intro_h": "Less paper, fewer mistakes",
        "intro": "Invoices, customer data and receipts belong in systems that talk to each other. We look at what you need, choose a tool that fits your business and budget, and set it up for you.",
        "bullets": [
            "Peppol-ready invoicing software, chosen and set up",
            "Your logo, VAT details and payment terms correct on every invoice",
            "A CRM with your customers, quotes and follow-ups",
            "A POS system for retail or hospitality, with a payment terminal",
            "Connections with your website and your accountant",
        ],
        "packages": [
            {"name": "Peppol Start", "price": "[[peppol]]", "featured": True, "items": ["Choosing software that fits you", "Setup with your details and logo", "Sending your first e-invoice together"], "cta": "Start with Peppol"},
            {"name": "CRM setup", "price": "[[crm]]", "from": True, "items": ["Importing customers and contacts", "Quotes and follow-up set up", "Connected to your website forms"], "cta": "Request a proposal"},
            {"name": "POS system", "price": "[[pos]]", "from": True, "items": ["Advice on till and payment terminal", "Products and prices entered", "Training for you and your team"], "cta": "Request a proposal"},
        ],
        "packages_note": "Software subscriptions and hardware are paid directly to the supplier. All prices excl. VAT.",
        "faq": [
            ("Do I have to use Peppol?", "For invoices to other Belgian businesses, a structured e-invoice via Peppol has been the rule since 1 January 2026. If you're unsure whether it applies to you, check with your accountant."),
            ("Which software do you recommend?", "It depends on your business. We choose together with you and your accountant. If a supplier pays us a commission, we tell you upfront."),
            ("Do you sell tills as well?", "We advise and set up your system. You buy the hardware and subscription directly from the supplier, so everything stays in your name."),
            ("Can enquiries from my website go straight into my CRM?", "Yes. Enquiries from your site land in your CRM automatically, with a notification for you."),
        ],
        "related": ["software", "chatbot", "website"],
    },
    "software": {
        "nav": "Software & integrations",
        "title": "Custom software and integrations | Rozmary Digital",
        "desc": "Losing time retyping data? We connect your webshop, supplier, CRM and accounting, and build custom software from €1,500. Start with a free time-saving scan.",
        "h1": "Software and integrations that give you your time back",
        "lead": "Retyping, copying and pasting is work for computers. We connect your systems and build what doesn't exist yet.",
        "chips": ["Free time-saving scan", "From [[software]]", "Tested and documented"],
        "card": "Integrations and custom software that save time.",
        "price_card": "[[software]]",
        "intro_h": "From manual work to automatic",
        "intro": "A supplier with thousands of products, orders you retype, reports you build by hand every month: all of that can be automatic. We start with a free call to see where most of your time goes.",
        "bullets": [
            "Connections between webshop, supplier, CRM and accounting",
            "Automatic prices and stock",
            "Dashboards and reports",
            "Forms and quotes that follow themselves up",
            "Documentation and tests, so it keeps working",
        ],
        "packages": [
            {"name": "Time-saving scan", "price": "[[scan]]", "items": ["30-minute call", "Overview of what you can automate", "Estimate of time saved and cost"], "cta": "Plan the scan"},
            {"name": "Integration or software", "price": "[[software]]", "from": True, "featured": True, "items": ["Analysis and fixed-price proposal", "Build and tests", "Documentation", "Maintenance by arrangement"], "cta": "Request a proposal"},
        ],
        "packages_note": "All prices excl. VAT.",
        "faq": [
            ("What have you connected so far?", "For Thunder Racing we're building a connection with a supplier catalogue of 27,503 products, with automatic pricing rules for the webshop."),
            ("How much does custom software cost?", "Small integrations start around [[software]]. After the time-saving scan you get a fixed price."),
            ("What if something goes wrong?", "Every integration has tests and alerts. With a maintenance contract, we keep an eye on everything for you."),
        ],
        "related": ["pos", "shop", "chatbot"],
    },
}

PRICE_GROUPS = [
    ("Free", None, [
        ("Growth scan", "Review of your website, Google profile, reviews and 3 competitors, plus a 15-minute call", "scan", False, False, "scan"),
        ("Ad check", "Three improvements for your campaigns or advertising plan", "scan", False, False, "ads"),
        ("Time-saving scan", "What can you automate, and what does it bring?", "scan", False, False, "software"),
    ]),
    ("Getting started", None, [
        ("Business Cards Start", "Design plus 250 printed cards, delivered to your door", "cards", False, False, "cards"),
        ("Digital business card", "Contact page with QR code, plus [[vcard_m]] per month", "vcard", False, False, "cards"),
        ("Google Profile Boost", "Profile fully set up, review link and 50 QR cards", "gbp", False, False, "google"),
        ("Webshop legal check", "Withdrawal button, warranty, cookies and privacy checked", "shopcheck", False, False, "shop"),
        ("Peppol Start", "Invoicing software chosen and set up, first e-invoice together", "peppol", False, False, "pos"),
        ("Logo Start", "3 concepts, 2 rounds of changes, all files", "logo", False, False, "brand"),
    ]),
    ("Packages", None, [
        ("Brand identity", "Logo, colours, fonts, business card, social templates, brand guide", "brand", False, False, "brand"),
        ("Website Start", "One-page site with copy, local SEO, WhatsApp button and tracking", "web_start", False, False, "website"),
        ("Starter Package", "Brand identity, Website Start, Google Profile Boost and 250 cards; or [[starter_m]] per month", "starter", False, False, "starter"),
        ("Website Growth", "8 to 15 pages, service and town pages, 2 languages", "web_grow", False, False, "website"),
        ("Webshop Start", "Shopify, 25 products, Bancontact, legal check included", "shop", False, True, "shop"),
    ]),
    ("Monthly plans", "maandplannen", [
        ("Carefree", "Hosting, SSL, backups, updates and 30 minutes of changes", "care", True, False, "website"),
        ("Local Growth Plan", "Carefree + Google profile management, review campaign, 1 SEO page, monthly report", "plan_local", True, False, "google"),
        ("Growth Plan Plus", "Local Growth Plan + 8 social posts, ad management, 2 SEO pages", "plan_plus", True, False, "ads"),
    ]),
    ("Extras", None, [
        ("Ad management", "Management, funnel and report; setup [[ads_setup]] one-off, budget separate", "ads_m", True, False, "ads"),
        ("Social media", "8 posts a month with planning and report", "social_m", True, False, "social"),
        ("AI chatbot", "On your own content, trilingual, AI Act compliant; plus [[bot_m]] per month", "bot", False, False, "chatbot"),
        ("Half-day photo shoot", "With our partner photographer, edited photos for web and print", "photo", False, False, "photo"),
        ("CRM setup", "Contacts, quotes and follow-up, linked to your site", "crm", False, True, "pos"),
        ("POS system", "Advice, setup and training; hardware separate", "pos", False, True, "pos"),
        ("Integration or software", "After a free time-saving scan, at a fixed price", "software", False, True, "software"),
    ]),
]

PAGES = {
    "home": {
        "title": "Rozmary Digital | Digital partner for small businesses",
        "desc": "Website, branding, Google profile, ads and invoicing from one partner in Belgium's Kempen region. Prices on the site, website live in 7 working days.",
        "eyebrow": "Digital partner for start-ups and small businesses",
        "h1a": "More customers from your own area.",
        "h1b": "One partner for everything.",
        "lead": "Website, branding, Google profile, advertising, social media and your till or invoicing. We set it up, measure what it brings in and stay your single point of contact.",
        "cta2": "See all prices",
        "trust": ["Prices right on the site", "Website live in 7 working days", "English, Dutch and French", "Everything in your name"],
        "tickets": [
            ("Website Start", "[[web_start]]", "One-page site, live in 7 working days"),
            ("Starter Package", "[[starter]]", "Or [[starter_m]] a month, no deposit"),
            ("Local Growth Plan", "[[plan_local]]/month", "More reviews, easier to find, monthly report"),
        ],
        "services_h": "Everything for your business, under one roof",
        "services_p": "Pick one service or let us handle the lot. Every service shows its price, excl. VAT.",
        "starter_h": "Just started? Get it all sorted in one go.",
        "starter_p": "The Starter Package gives you a logo and brand identity, 250 business cards, a website and a Google profile ready for your first reviews.",
        "starter_items": ["Logo and brand identity", "250 business cards", "Website Start", "Google profile set up"],
        "starter_price_note": "or [[starter_m]] a month, no deposit",
        "starter_cta": "See the Starter Package",
        "method_h": "Marketing in five steps, without the jargon",
        "method_p": "Every service we sell belongs to one of these steps. So you always know why you're investing in something.",
        "method_loop": "Every month we measure what works and adjust.",
        "method_cta": "See how we work",
        "work_h": "Recent work in the Kempen region",
        "work_cta": "All our work",
        "why_h": "Why Rozmary",
        "why": [
            ("Prices on the site", "You know upfront what it costs. No ‘request a quote’ for every little thing."),
            ("One point of contact", "From business card to webshop: one person who knows your business and follows up on everything."),
            ("Fast, never rushed", "We work with smart AI tools. Every text, design and line of code is checked by us."),
            ("Local and reachable", "Based in the Kempen region, reachable on WhatsApp, and happy to visit you."),
            ("Measurable", "Every site counts calls, WhatsApp messages and enquiries. You get a clear monthly report."),
            ("Everything in your name", "Domain, copy and accounts stay yours. You can stop at any time."),
        ],
        "plans_h": "After launch: a fixed monthly plan",
        "plans_p": "A site nobody maintains loses ground. Our monthly plans keep you findable, secure and up to date.",
        "plans": [
            ("Carefree", "care", ["Hosting and SSL", "Backups and updates", "30 minutes of changes per month"]),
            ("Local Growth Plan", "plan_local", ["Everything in Carefree", "Google profile management and review campaign", "One new SEO page per month", "Monthly report"]),
            ("Growth Plan Plus", "plan_plus", ["Everything in Local Growth Plan", "8 social media posts per month", "Ad management (budget separate)", "Quarterly review"]),
        ],
        "plans_cta": "Compare all prices",
        "faq": [
            ("How much does a website from Rozmary cost?", "A one-page website costs [[web_start]] excl. VAT, a site with 8 to 15 pages [[web_grow]]. Rather not pay a deposit? Choose the Starter Package at [[starter_m]] a month."),
            ("Can't ChatGPT just build my website?", "AI can put together a first version, and we use it too. The difference is what comes next: the right keywords, fast technology, accurate copy, tracking and someone who steps in when something goes wrong."),
            ("How fast is my site online?", "A one-page site goes live within 7 working days after we receive your logo, copy and photos. If we miss that, you get [[late_discount]] off."),
            ("Am I tied to a long contract?", "No. Monthly plans run for at least 3 months and can then be cancelled monthly. Your domain and your site remain yours."),
            ("Do you work outside the Kempen region?", "Yes. We work across Flanders, Brussels and Wallonia, in English, Dutch or French. In the Kempen region we're happy to visit you."),
        ],
    },
    "pricing": {
        "title": "Website, logo and marketing prices 2026 | Rozmary",
        "desc": "All Rozmary Digital prices on one page: website from €995, logo from €249, business cards €119, monthly plans from €29. Excl. VAT, with no surprises.",
        "h1": "All our prices, in one place",
        "lead": "No ‘request a quote’ for every little thing. Here's what everything costs, excl. VAT. Not sure yet? The growth scan is free.",
        "col_product": "Product", "col_what": "What you get", "col_price": "Price",
        "rules_h": "Terms",
        "rules": [
            "All prices are excl. VAT.",
            "Projects: 50% deposit, the rest on delivery.",
            "Monthly plans: minimum 3 months, then cancel monthly, by direct debit.",
            "Starter Package paid monthly: 24 months, after which only Carefree continues.",
            "Guarantee: live within 7 working days after your input, or [[late_discount]] off. Two rounds of changes included.",
        ],
        "faq": [
            ("Why are your prices online?", "Because as a business owner you want to know where you stand. And because it saves us time we'd rather spend on your project."),
            ("Are there hidden costs?", "No. Only what you pay third parties directly, such as your domain name, Shopify, ad budget or software subscriptions. We always tell you upfront."),
            ("Can I get a discount?", "The Starter Package is 20% cheaper than its parts bought separately. Otherwise we keep one price for everyone."),
        ],
    },
    "method": {
        "title": "How we work: marketing in 5 steps | Rozmary Digital",
        "desc": "From vision to loyal customer: how we approach marketing for small businesses. Five steps without jargon, measured and adjusted every month.",
        "h1": "Marketing in five steps, without the jargon",
        "lead": "Marketing isn't a mystery. It's five steps that follow each other. We look at where your business is losing customers and start there.",
        "loop_h": "Measure and adjust every month",
        "loop_p": "Every month you get a short report: how many people found you, called, sent a WhatsApp or made an enquiry, and how many new reviews you received. Based on that, we choose the next step.",
        "project_h": "How a project runs",
    },
    "work": {
        "title": "Our work: websites and marketing in the Kempen | Rozmary",
        "desc": "Our work for Shiny Cleaning and Thunder Racing in Geel: local SEO websites, branding, stock management and a webshop integration with 27,503 products.",
        "h1": "Our work",
        "lead": "Two local businesses, two different questions. Here's how we approached them.",
        "visit": "Visit the site",
        "cases": {
            "shiny": {
                "sector": "Window cleaner and cleaning company",
                "question": "A one-page site that hardly anyone found, with no prices, and therefore few enquiries.",
                "did": ["Positioned as the outdoor cleaning specialist of the Kempen region", "Keyword research: ‘ruitenwasser’ is searched 1.75 times more often than ‘glazenwasser’", "Ten service pages and seventeen town pages, each with its own local copy", "A pricing page, WhatsApp as the first button and a homepage in Dutch, French and English"],
                "facts": [("34", "pages"), ("17", "towns"), ("3", "languages")],
            },
            "thunder": {
                "sector": "Scooter garage and shop",
                "question": "A growth audit revealed the weak spots: everything sat on one page and no stock or prices were visible.",
                "did": ["Growth audit of the site, reviews and competitors", "New 26-page site by service, brand and town", "Admin page to update stock, prices and reviews yourself", "Integration with supplier PePe Parts' catalogue for the webshop, in development"],
                "facts": [("26", "pages"), ("27,503", "products connected"), ("59", "automated tests")],
            },
        },
    },
    "about": {
        "title": "About Rozmary Digital: your digital partner in Belgium",
        "desc": "Rozmary Digital is a digital agency for start-ups and small businesses. One point of contact, fixed prices and smart AI tools, always checked by a person.",
        "h1": "One partner for everything digital",
        "lead": "Rozmary Digital helps start-ups and small businesses win more customers, with websites, branding, marketing and the tools behind them.",
        "sections": [
            ("Who we are", "Behind Rozmary Digital is Sebastiaan, trained in business management and IT. He is your single point of contact: he listens to your business, safeguards the quality and follows up on everything. For photo, video and print we work with regular partners from the region."),
            ("How we use AI", "We use smart AI tools for research, copy, design and code. That lets us deliver faster and at a better price. Every text, design and line of code is checked by a person before it goes live for you."),
            ("Where the name comes from", "Rozmary refers to rosemary: a plant that grows all year round, is tough and stays green. It has long stood for remembrance. Exactly what a good partner does."),
        ],
        "values_h": "What you can expect from us",
        "values": ["Prices agreed upfront", "One point of contact, reachable on WhatsApp", "Domain, copy and accounts in your name", "No long contracts", "Honest advice, even when that's ‘not needed yet’"],
        "area_h": "Where we work",
        "area_p": "Our home base is the Kempen region in the province of Antwerp, where we're happy to visit you. Online we work across Flanders, Brussels and Wallonia, in English, Dutch and French.",
    },
    "contact": {
        "title": "Contact us | Rozmary Digital",
        "desc": "Send us a WhatsApp message, email us or fill in the form. We reply within one working day, and in the Kempen region we're happy to visit you.",
        "h1": "Contact",
        "lead": "A question, an idea or ready to start? Send a message and we'll reply within one working day.",
        "wa_h": "WhatsApp", "wa_p": "The fastest way. Send a message and we'll reply as soon as we can.",
        "mail_h": "Email", "mail_p": "Prefer email? That's always fine.",
        "form_h": "Or fill in the form",
        "visit_h": "Meet in person", "visit_p": "In the Kempen region we're happy to visit you for an introduction.",
    },
    "scan": {
        "title": "Free growth scan for your website | Rozmary Digital",
        "desc": "Ask for a free growth scan: we check your website, Google profile, reviews and three competitors, and discuss in 15 minutes where you're losing customers.",
        "h1": "Free growth scan: where is your business losing customers?",
        "lead": "We review your website, your Google profile, your reviews and three competitors. In a 15-minute call you get the three most important improvements. Free and without obligation.",
        "check_h": "What we check",
        "checks": ["Speed and mobile use", "Visibility for your most important search terms", "Your Google profile and reviews", "How easily a visitor can contact you", "How you compare with three competitors", "What to tackle first"],
        "form_h": "Request your growth scan",
        "no_site": "No website yet? Then we review your Google profile, your social media and your competitors.",
    },
    "privacy": {
        "title": "Privacy policy | Rozmary Digital",
        "desc": "How Rozmary Digital handles your data: which data we receive through forms, why, how long we keep it and what your rights are.",
        "h1": "Privacy policy",
        "lead": "In short: we only use your data to help you and to reply to you.",
        "sections": [
            ("Who is responsible?", "Rozmary Digital, [[legal]], is responsible for processing your personal data. You can send questions to [[email]]."),
            ("Which data?", "What you fill in on a form or send via WhatsApp or email: your name, company, email address, phone number, website, town and your message."),
            ("Why?", "To answer your question, prepare a growth scan or proposal and, if you become a client, to perform our agreement and invoice you."),
            ("How long?", "Enquiries that don't become a project are deleted after 12 months. Client data is kept as long as the law requires, for example 10 years for invoices."),
            ("Cookies", "This website does not use tracking or advertising cookies. Only what is strictly necessary for the site to work."),
            ("Who do we share with?", "Only with service providers we need to work, such as our hosting (Hostinger) and email. We never sell your data."),
            ("Your rights", "You can always view, correct or delete your data. Email [[email]]. If you're not satisfied, you can contact the Belgian Data Protection Authority (dataprotectionauthority.be)."),
        ],
    },
    "thanks": {
        "title": "Thank you | Rozmary Digital",
        "desc": "Thank you for your message to Rozmary Digital. We reply within one working day.",
        "h1": "Thank you, we've received your message",
        "lead": "We reply within one working day. In a hurry? Send us a WhatsApp right away.",
        "back": "Back to the homepage",
    },
    "404": {
        "title": "Page not found | Rozmary Digital",
        "h1": "This page doesn't exist (any more)",
        "lead": "You might find what you're looking for here:",
    },
}

MODEL = [
    ("Vision", "Who are you the best choice for?", "We define your audience, your offer and your prices. So everyone knows why they should choose you.", ["starter", "brand"]),
    ("Visibility", "Are you found where your customers search?", "Google, your Google profile, advertising and social media: we make you visible at the moment someone searches.", ["google", "ads", "social"]),
    ("Trust", "Why should they choose you?", "A site, reviews, real photos and examples that show why they should pick you over the competition.", ["website", "photo", "cards"]),
    ("Conversion", "Does a visitor become a customer?", "WhatsApp, quote, appointment or online payment, with automatic follow-up. No enquiry gets lost.", ["shop", "chatbot", "pos"]),
    ("Retention", "Does the customer come back and bring others?", "Asking for reviews, a newsletter and maintenance. A loyal customer costs less than a new one.", ["software", "social"]),
]
