"""Contenu français (Belgique). Prix via [[clé]] (voir siteconf.py)."""

N = " "  # espace insécable (avant ? ! : et €)

UI = {
    "skip": "Aller au contenu",
    "menu": "Menu", "close": "Fermer",
    "nav_services": "Services", "nav_pricing": "Tarifs", "nav_method": "Méthode",
    "nav_work": "Réalisations", "nav_about": "À propos", "nav_contact": "Contact",
    "cta_scan": "Scan gratuit", "whatsapp": "WhatsApp", "whatsapp_long": "Envoyer un WhatsApp",
    "from": "dès", "per_month": "/mois", "per_month_long": "par mois", "excl": "hors TVA",
    "free": "gratuit", "on_quote": "sur devis", "more": "En savoir plus", "home": "Accueil",
    "packages_h": "Formules et tarifs", "steps_h": "Comment ça marche", "faq_h": "Questions fréquentes",
    "related_h": "À découvrir aussi", "all_services": "Tous les services", "all_prices": "Tous les tarifs",
    "footer_services": "Services", "footer_company": "Rozmary", "footer_contact": "Contact",
    "footer_area": "Zone d'activité", "footer_tagline": "Partenaire digital des indépendants et des PME.",
    "kbo": "Numéro d'entreprise", "kbo_missing": "Numéro d'entreprise à venir", "privacy": "Confidentialité",
    "rights": "Tous les prix hors TVA.", "lang_label": "Langue",
    "cta_band_h": f"Où votre entreprise perd-elle des clients{N}?",
    "cta_band_p": f"Demandez un scan de croissance gratuit{N}: nous analysons votre site, votre fiche Google, vos avis et trois concurrents, puis nous en parlons en 15 minutes.",
    "breadcrumb": "Fil d'Ariane",
    "wa_general": "Bonjour Rozmary Digital, j'ai une question.",
    "wa_service": "Bonjour Rozmary Digital, j'ai une question sur : {s}.",
    "region": "Campine", "recommended": "Recommandé",
    "form": {
        "name": "Nom", "company": "Entreprise (facultatif)", "email": "E-mail",
        "phone": "Téléphone (facultatif)", "website": "Site web (si vous en avez un)",
        "city": "Commune", "interest": f"Comment pouvons-nous vous aider{N}?", "other": "Autre chose",
        "message": "Votre message", "consent": "Rozmary Digital peut utiliser mes données pour me recontacter.",
        "consent_link": "Confidentialité", "submit": "Envoyer", "sending": "Envoi en cours…",
        "ok": f"Merci{N}! Nous répondons dans un délai d'un jour ouvrable.",
        "fail": "L'envoi a échoué. Envoyez votre message via WhatsApp ou par e-mail.",
        "wa_fallback": "Envoyer via WhatsApp", "required": "Champ obligatoire",
        "wa_intro": "Bonjour Rozmary Digital, ",
    },
}

STEPS = [
    ("Premier contact", "En 15 minutes, nous parlons de votre activité, de votre objectif et de votre budget."),
    ("Proposition à prix fixe", f"Vous recevez une proposition claire. D'accord{N}? Vous payez un acompte de 50{N}%."),
    ("Nous réalisons, vous validez", "Vous suivez tout et vous disposez de deux tours de corrections."),
    ("En ligne et suivi", "Nous lançons, mesurons les résultats et proposons une formule mensuelle si c'est utile."),
]

SERVICES = {
    "website": {
        "nav": "Site internet",
        "title": f"Création de site internet dès 995{N}€ | Rozmary",
        "desc": f"Création de site internet pour indépendants et PME{N}: site one-page dès 995{N}€, site complet dès 2{N}495{N}€. Textes, SEO local et bouton WhatsApp inclus.",
        "h1": "Création de site internet dès [[web_start]]",
        "lead": "Un site rapide et bien référencé, qui transforme les visiteurs en demandes. Textes, SEO local, bouton WhatsApp et mesures inclus.",
        "chips": ["En ligne en 7 jours ouvrables", "Textes inclus", "Nom de domaine à votre nom"],
        "card": "Site rapide et bien référencé, avec textes et bouton WhatsApp.",
        "price_card": "[[web_start]]",
        "intro_h": "Un site qui travaille pour vous",
        "intro": "La plupart des indépendants n'ont pas besoin d'un site plus joli, mais d'un site qu'on trouve et qui génère des demandes. Nous construisons donc chaque site autour des recherches de vos clients et d'une action claire.",
        "bullets": [
            "Des textes basés sur ce que vos clients recherchent vraiment",
            "Une page par service et par commune si vous le souhaitez",
            "Boutons WhatsApp, appel et devis sur chaque page",
            "Mesure des appels, des messages et des demandes",
            f"Techniquement irréprochable{N}: rapide, mobile, sécurisé, avec des données Google correctes",
        ],
        "packages": [
            {"name": "Site Start", "price": "[[web_start]]", "items": ["Site one-page jusqu'à 6 sections", "Textes et mots-clés inclus", "Boutons WhatsApp, appel et devis", "Réglages Google de base et mesures", "En ligne en 7 jours ouvrables"], "cta": "Lancer mon site"},
            {"name": "Site Croissance", "price": "[[web_grow]]", "featured": True, "items": ["8 à 15 pages", "Une page par service et par commune", "Deux langues au choix", "Blog ou actualités", "Page tarifs et FAQ"], "cta": "Demander une proposition"},
            {"name": "Pack démarrage", "price": "[[starter]]", "note": "ou [[starter_m]] par mois", "items": ["Site Start", "Logo et identité visuelle", "250 cartes de visite", "Fiche Google configurée"], "cta": "Voir le pack", "link": "starter"},
        ],
        "packages_note": f"Hébergement et maintenance{N}: formule Sérénité à [[care]] par mois. Tous les prix hors TVA.",
        "faq": [
            (f"Combien coûte la création d'un site internet{N}?", f"Chez nous, [[web_start]] pour un site one-page et [[web_grow]] pour un site de 8 à 15 pages, hors TVA. En Belgique, les prix vont de 550{N}€ chez un freelance à 7{N}000{N}€ ou plus dans les grandes agences."),
            (f"Puis-je payer mon site par mois{N}?", "Oui. Avec le Pack démarrage, vous payez [[starter_m]] par mois pendant 24 mois, sans acompte. Hébergement et maintenance compris."),
            (f"ChatGPT peut-il créer un site internet{N}?", f"Il peut produire une première ébauche. Il manque tout le reste{N}: recherche de mots-clés, hébergement rapide, données Google correctes, mesures et quelqu'un qui entretient votre site. C'est notre travail, et nous utilisons l'IA pour le rendre plus rapide et plus abordable."),
            (f"À qui appartient le site une fois terminé{N}?", "À vous. Le nom de domaine est à votre nom et vous recevez tous les fichiers. Si vous arrêtez notre maintenance, nous vous aidons à déménager."),
        ],
        "related": ["starter", "google", "brand"],
    },
    "starter": {
        "nav": "Pack démarrage",
        "title": f"Pack démarrage pour indépendants{N}: 1{N}495{N}€ | Rozmary",
        "desc": f"Vous vous lancez ? Logo, identité visuelle, 250 cartes de visite, site internet et fiche Google en un seul pack : 1{N}495{N}€ ou 99{N}€ par mois sans acompte.",
        "h1": "Pack démarrage : tout pour vous lancer pour [[starter]]",
        "lead": "Logo, identité visuelle, cartes de visite, site internet et fiche Google en une fois. Aussi payable par mois, sans acompte.",
        "chips": ["Ou [[starter_m]] par mois", "Prêt en 3 semaines", "Un seul interlocuteur"],
        "card": "Logo, cartes de visite, site et fiche Google en un seul pack.",
        "price_card": "[[starter]]",
        "intro_h": "Une première impression réussie",
        "intro": "Quand on démarre, on a déjà beaucoup à gérer. Avec le Pack démarrage, votre entreprise est présentée de façon professionnelle, en ligne et sur papier, sans cinq fournisseurs différents.",
        "bullets": [
            f"Logo et identité visuelle{N}: couleurs, polices et mini-charte",
            "250 cartes de visite imprimées, livrées chez vous",
            f"Site Start{N}: site one-page avec textes et bouton WhatsApp",
            "Fiche Google configurée, avec lien d'avis et cartes QR",
            f"En paiement mensuel{N}: hébergement et maintenance inclus",
        ],
        "packages": [
            {"name": "En une fois", "price": "[[starter]]", "featured": True, "items": ["Logo et identité visuelle", "250 cartes de visite", "Site Start", "Boost fiche Google"], "cta": "Choisir le pack"},
            {"name": "Par mois", "price": "[[starter_m]]", "per": True, "items": ["Le même pack, sans acompte", "Hébergement et maintenance inclus", "24 mois, ensuite Sérénité à [[care]] par mois", "Nom de domaine à votre nom"], "cta": "Payer par mois"},
        ],
        "packages_note": "Acheté séparément, l'ensemble coûte [[starter_loose]]. Tous les prix hors TVA.",
        "steps": [
            ("Premier contact", "En 15 minutes, nous parlons de votre activité, de vos clients et de votre style."),
            ("Identité visuelle (semaine 1)", "Vous recevez trois propositions de logo et deux tours de corrections."),
            ("Site et impression (semaine 2)", "Nous construisons votre site et commandons vos cartes de visite."),
            ("En ligne et visible (semaine 3)", "Votre site est en ligne et votre fiche Google est prête pour vos premiers avis."),
        ],
        "faq": [
            (f"Que contient exactement le Pack démarrage{N}?", "Un logo avec identité visuelle et mini-charte, 250 cartes de visite imprimées, un site one-page avec textes et bouton WhatsApp, et une fiche Google complète avec lien d'avis et cartes QR."),
            (f"Puis-je payer le pack par mois{N}?", "Oui, [[starter_m]] par mois pendant 24 mois, sans acompte. Hébergement et maintenance compris."),
            (f"J'ai déjà un logo. Le pack peut-il être adapté{N}?", "Bien sûr. Nous remplaçons alors l'identité visuelle par ce dont vous avez besoin, comme des pages en plus ou des imprimés."),
            (f"Combien de temps faut-il{N}?", "En moyenne trois semaines, selon la rapidité de vos retours."),
        ],
        "related": ["website", "brand", "cards"],
    },
    "brand": {
        "nav": "Logo & identité visuelle",
        "title": f"Création de logo dès 249{N}€ | Identité visuelle | Rozmary",
        "desc": f"Création de logo ou d'identité visuelle : logo dès 249{N}€, identité complète avec carte de visite et modèles réseaux sociaux à 595{N}€. Prix fixe.",
        "h1": "Création de logo et d'identité visuelle, dès [[logo]]",
        "lead": "Un logo reconnaissable et une identité qui reste cohérente partout : sur votre façade, votre site, votre camionnette et Instagram.",
        "chips": ["3 propositions", "2 tours de corrections", "Tous les fichiers"],
        "card": "Un logo reconnaissable et une identité cohérente partout.",
        "price_card": "[[logo]]",
        "intro_h": "Bien plus qu'un logo",
        "intro": "Aujourd'hui, on crée un logo en cinq minutes avec une appli. Une identité visuelle qui parle à vos clients et fonctionne à toutes les tailles, c'est autre chose. Nous la construisons avec vous.",
        "bullets": [
            "Logo en couleur, en noir et blanc et en icône",
            "Palette de couleurs et polices",
            "Carte de visite et signature e-mail",
            "Modèles pour Instagram et Facebook",
            "Mini-charte pour que chacun utilise votre style correctement",
        ],
        "packages": [
            {"name": "Logo Start", "price": "[[logo]]", "items": ["3 propositions de logo", "2 tours de corrections", "Fichiers web et impression (SVG, PNG, PDF)"], "cta": "Commander Logo Start"},
            {"name": "Identité visuelle", "price": "[[brand]]", "featured": True, "items": ["Tout Logo Start", "Couleurs et polices", "Design de votre carte de visite", "Modèles pour les réseaux sociaux", "Mini-charte"], "cta": "Créer mon identité"},
        ],
        "packages_note": "Tous les prix hors TVA. Après paiement, tous les droits vous appartiennent.",
        "faq": [
            (f"Combien coûte la création d'un logo{N}?", f"Chez nous, [[logo]] pour Logo Start et [[brand]] pour une identité visuelle complète, hors TVA. En ligne, un simple logo coûte de 99 à 279{N}€."),
            (f"ChatGPT peut-il créer un logo{N}?", "Les outils d'IA créent vite un visuel, mais souvent sans caractère unique, sans fichiers exploitables et sans certitude sur les droits. Nous utilisons l'IA pour des esquisses rapides, puis nous dessinons le logo nous-mêmes."),
            (f"Où créer un logo gratuitement{N}?", "Avec des outils comme Canva, et pour un premier test, c'est très bien. Si vous voulez un logo net à toutes les tailles et adapté à vos clients, un design sur mesure vaut la peine."),
            (f"À qui appartiennent les droits{N}?", "Après paiement, tous les droits sur le logo et l'identité visuelle vous appartiennent."),
        ],
        "related": ["cards", "starter", "social"],
    },
    "cards": {
        "nav": "Cartes de visite",
        "title": f"Cartes de visite{N}: design + impression 119{N}€ | Rozmary",
        "desc": f"Cartes de visite dessinées et imprimées pour vous : 250 cartes à votre image pour 119{N}€, livrées. Ou une carte digitale avec code QR pour 79{N}€.",
        "h1": "Cartes de visite : design et impression pour [[cards]]",
        "lead": "Vous ne dessinez rien et ne commandez rien vous-même. Nous créons le design à votre image, puis faisons imprimer et livrer 250 cartes.",
        "chips": ["250 cartes incluses", "Livrées chez vous", "Aussi en digital"],
        "card": "Design et impression de 250 cartes, ou une carte digitale.",
        "price_card": "[[cards]]",
        "intro_h": "Des cartes qui vous ressemblent",
        "intro": "Un imprimeur en ligne est bon marché, mais vous devez tout dessiner vous-même. Nous veillons à ce que votre carte corresponde à votre logo, votre site et votre façade, avec chaque info au bon endroit.",
        "bullets": [
            "Design recto verso à votre image",
            "Vérification de toutes les données et fichier prêt à imprimer",
            "250 cartes sur papier épais, livrées chez vous",
            f"En option{N}: une carte de visite digitale avec code QR",
        ],
        "packages": [
            {"name": "Cartes de visite Start", "price": "[[cards]]", "featured": True, "items": ["Design à votre image", "250 cartes imprimées", "Livraison en Belgique"], "cta": "Commander mes cartes"},
            {"name": "Carte de visite digitale", "price": "[[vcard]]", "note": "+ [[vcard_m]] par mois", "items": ["Page de contact avec vos coordonnées", "Code QR pour votre carte ou votre façade", "Bouton pour enregistrer votre contact", "Modifications incluses"], "cta": "Commander en digital"},
        ],
        "packages_note": "Tous les prix hors TVA.",
        "faq": [
            (f"Puis-je commander uniquement le design{N}?", "Oui, vous recevez alors un fichier prêt à imprimer. Demandez-le via WhatsApp ou le formulaire de contact."),
            (f"Combien de temps faut-il{N}?", "Après validation du design, vos cartes arrivent généralement dans la semaine."),
            (f"Qu'est-ce qu'une carte de visite digitale{N}?", "Une page web avec vos coordonnées, des boutons pour appeler ou écrire et un bouton pour enregistrer votre contact. Avec un code QR, vous la partagez en une seconde."),
            (f"Je n'ai pas encore de logo. Que faire{N}?", "Commencez par Logo Start ou par le Pack démarrage, qui inclut déjà 250 cartes."),
        ],
        "related": ["brand", "starter", "google"],
    },
    "google": {
        "nav": "Fiche Google",
        "title": f"Optimiser votre fiche Google Business{N}: 149{N}€ | Rozmary",
        "desc": f"Mieux classé sur Google Maps dans votre commune{N}: nous configurons entièrement votre fiche d'établissement Google pour 149{N}€, avec lien d'avis et cartes QR.",
        "h1": "Optimisation de votre fiche Google pour [[gbp]]",
        "lead": "Quand on cherche dans votre commune, on voit d'abord la carte avec trois entreprises. Nous faisons en sorte que vous y soyez, avec des photos, des services et des avis qui convainquent.",
        "chips": ["Fiche entièrement configurée", "Lien d'avis et cartes QR", "Mots-clés locaux"],
        "card": "Plus visible sur Google Maps, avec plus d'avis.",
        "price_card": "[[gbp]]",
        "intro_h": "La carte remporte le clic",
        "intro": "Pour une recherche comme ‘coiffeur Geel’, trois entreprises apparaissent sur la carte, au-dessus de tous les autres résultats. Les avis, la complétude et l'activité font la différence. C'est exactement ce que nous gérons pour vous.",
        "bullets": [
            "Catégories, services, horaires et zone d'intervention correctement réglés",
            "Dix photos et une description avec vos mots-clés",
            "Votre propre lien d'avis et 50 cartes QR",
            "Lien avec votre site et mesure des clics",
            "Des conseils pour rester visible chaque semaine",
        ],
        "packages": [
            {"name": "Boost fiche Google", "price": "[[gbp]]", "featured": True, "items": ["Fiche entièrement configurée", "Lien d'avis et 50 cartes QR", "Mots-clés locaux dans votre description"], "cta": "Booster ma fiche"},
            {"name": "Plan Croissance Local", "price": "[[plan_local]]", "per": True, "items": ["Deux publications par semaine sur votre fiche", "Campagne d'avis par WhatsApp et e-mail", "Une nouvelle page SEO par mois", "Hébergement, maintenance et rapport mensuel"], "cta": "Démarrer le plan"},
        ],
        "packages_note": "Tous les prix hors TVA. Plans mensuels : minimum 3 mois, puis résiliables chaque mois.",
        "faq": [
            (f"Comment être mieux classé sur Google Maps{N}?", "Avec une fiche complète, la bonne catégorie, des mises à jour régulières et surtout beaucoup d'avis récents et authentiques. En Campine, le top 3 compte souvent moins de 50 avis, c'est donc atteignable."),
            (f"Écrivez-vous des avis pour moi{N}?", "Non. Les faux avis sont interdits et vous nuisent. Nous rendons par contre très simple, pour vos clients, le fait d'en laisser un."),
            (f"Je n'ai pas de magasin. Puis-je avoir une fiche{N}?", "Oui. Si vous vous déplacez chez vos clients, vous indiquez une zone d'intervention et vous masquez votre adresse."),
            (f"J'ai déjà une fiche. Que faites-vous{N}?", "Nous la reprenons, complétons ce qui manque et corrigeons les erreurs."),
        ],
        "related": ["website", "ads", "social"],
    },
    "shop": {
        "nav": "Boutique en ligne",
        "title": f"Création de boutique en ligne dès 2{N}995{N}€ | Rozmary",
        "desc": f"Boutique en ligne Shopify dès 2{N}995{N}€ pour 25 produits, avec Bancontact et les obligations légales de 2026. Ou d'abord un check légal pour 149{N}€.",
        "h1": "Création de boutique en ligne dès [[shop]]",
        "lead": "Une boutique Shopify que vous gérez vous-même, avec Bancontact, livraison et les nouvelles obligations légales de 2026 en ordre.",
        "chips": ["Shopify", "Bancontact et carte", "En règle"],
        "card": "Boutique Shopify avec Bancontact, prête pour les règles de 2026.",
        "price_card": "[[shopcheck]]",
        "intro_h": "Vendre sans prise de tête",
        "intro": "Une boutique en ligne, c'est plus que mettre des produits en ligne. Paiement, livraison, retours et règles doivent être corrects. Depuis juin 2026, chaque e-shop doit par exemple afficher un bouton de rétractation clair.",
        "bullets": [
            "Boutique Shopify à votre image",
            "25 produits encodés, avec photos et textes",
            "Paiement par Bancontact et carte",
            "Zones de livraison, TVA et retours configurés",
            "Bouton de rétractation, infos de garantie et conditions conformes aux règles de 2026",
        ],
        "packages": [
            {"name": "Check légal e-shop", "price": "[[shopcheck]]", "items": ["Bouton et formulaire de rétractation", "Infos de garantie et allégations écologiques", "Cookies, vie privée et conditions", "Liste d'actions par priorité"], "cta": "Vérifier ma boutique"},
            {"name": "E-shop Start", "price": "[[shop]]", "from": True, "featured": True, "items": ["Boutique Shopify à votre image", "25 produits encodés", "Bancontact, livraison et TVA configurés", "Check légal inclus", "Formation d'une heure"], "cta": "Demander une proposition"},
        ],
        "packages_note": "L'abonnement Shopify est payé directement à Shopify. Tous les prix hors TVA.",
        "faq": [
            (f"Combien coûte la création d'une boutique en ligne{N}?", f"Chez nous, dès [[shop]] hors TVA pour une boutique Shopify avec 25 produits. En Belgique, les prix vont de 1{N}250 à 25{N}000{N}€ ou plus selon le sur-mesure et les connexions. S'y ajoute l'abonnement Shopify, dès 24{N}€ environ par mois."),
            (f"Pourquoi Shopify{N}?", "C'est fiable et sûr, et vous le gérez vous-même sans connaissances techniques. Pour les grands catalogues ou des connexions spéciales, nous développons sur mesure."),
            (f"Quelles règles s'appliquent aux e-shops en 2026{N}?", "Depuis le 19 juin 2026, un bouton de rétractation clair est obligatoire, et depuis le 27 septembre 2026, de nouvelles règles s'appliquent aux infos de garantie et aux allégations écologiques. Notre check légal fait le point pour vous."),
            (f"Pouvez-vous connecter mon fournisseur{N}?", "Oui. Pour Thunder Racing, nous développons une connexion avec le catalogue d'un fournisseur, avec prix et stock automatiques."),
        ],
        "related": ["ads", "photo", "software"],
    },
    "ads": {
        "nav": "Publicité & tunnels",
        "title": "Google Ads et publicité Facebook et Instagram | Rozmary",
        "desc": f"Publicité Google, Facebook et Instagram avec un tunnel de vente qui génère des demandes. Gestion dès 199{N}€ par mois plus budget. D'abord un check gratuit.",
        "h1": "Publicité en ligne et tunnels de vente",
        "lead": "Des annonces sur Google, Facebook et Instagram, reliées à une page d'atterrissage et à un suivi automatique. Chaque mois, vous voyez ce qu'elles rapportent.",
        "chips": ["Gestion dès [[ads_m]] par mois", "Budget séparé et transparent", "Rapport mensuel"],
        "card": "Des annonces avec un tunnel qui génère des demandes.",
        "price_card": "[[ads_m]]", "price_card_per": True,
        "intro_h": "Un clic n'est pas encore un client",
        "intro": f"Les clics coûtent cher{N}: en Belgique, un clic sur ‘website laten maken’ coûte facilement 13{N}€. Nous ne lançons donc la publicité que lorsque la page d'atterrissage est prête à convertir, et nous suivons chaque demande automatiquement.",
        "bullets": [
            "Campagnes sur Google Search, Google Maps, Facebook et Instagram",
            "Une page d'atterrissage par campagne, avec une action claire",
            "Suivi automatique par e-mail ou WhatsApp",
            "Mesure des demandes, pas seulement des clics",
            "Un rapport mensuel en langage clair",
        ],
        "packages": [
            {"name": "Check publicité", "price": "[[scan]]", "items": ["Nous analysons vos campagnes ou votre projet", "Trois améliorations concrètes", "Entretien de 15 minutes"], "cta": "Demander le check"},
            {"name": "Gestion publicitaire", "price": "[[ads_m]]", "per": True, "featured": True, "items": ["Mise en place des campagnes : [[ads_setup]] une fois", "Gestion et optimisation", "Tunnel de vente avec e-mails de suivi", "Rapport mensuel", "Minimum 3 mois"], "cta": "Lancer la publicité"},
        ],
        "packages_note": "Votre budget publicitaire est payé directement à Google ou Meta. Tous les prix hors TVA.",
        "faq": [
            (f"De quel budget ai-je besoin{N}?", f"Pour des campagnes locales, nous conseillons au moins 300{N}€ par mois. C'est possible avec moins, mais les résultats fiables prennent plus de temps."),
            (f"Qu'est-ce qu'un tunnel de vente{N}?", f"Le chemin du premier clic jusqu'au client{N}: annonce, page d'atterrissage, demande et suivi. Nous construisons et mesurons chaque étape."),
            (f"Promettez-vous plus de chiffre d'affaires{N}?", "Non. Personne ne peut le promettre honnêtement. Nous promettons par contre que vous voyez chaque mois ce que vos annonces rapportent et ce que nous ajustons."),
            (f"Pourquoi ne pas simplement booster mes posts sur Facebook{N}?", "Booster rapporte surtout des likes. Une campagne avec un objectif, un public et des mesures rapporte des demandes."),
        ],
        "related": ["website", "social", "google"],
    },
    "social": {
        "nav": "Réseaux sociaux",
        "title": f"Gestion des réseaux sociaux dès 349{N}€ par mois | Rozmary",
        "desc": f"Confiez vos réseaux sociaux : huit publications par mois pour Instagram et Facebook à votre image, avec planning et rapport, pour 349{N}€ par mois.",
        "h1": "Gestion des réseaux sociaux dès [[social_m]] par mois",
        "lead": "Huit publications réfléchies par mois pour Instagram et Facebook, à votre image et programmées. Vous validez, nous faisons le reste.",
        "chips": ["8 publications par mois", "Vous validez", "Rapport mensuel"],
        "card": "Huit publications par mois à votre image, programmées.",
        "price_card": "[[social_m]]", "price_card_per": True,
        "intro_h": "Rester visible, sans stress",
        "intro": "Les réseaux sociaux fonctionnent si vous publiez régulièrement et apportez quelque chose à vos clients. C'est rarement possible à côté de votre vrai travail. Nous faisons un planning mensuel, rédigeons les publications et les programmons.",
        "bullets": [
            "Planning mensuel adapté à votre saison et à vos actions",
            "Huit publications avec texte et visuel à votre image",
            "Programmation sur Instagram et Facebook",
            "Rapport mensuel avec portée et messages",
            "Shooting photo ou vidéo avec notre partenaire, si vous le souhaitez",
        ],
        "packages": [
            {"name": "Réseaux sociaux", "price": "[[social_m]]", "per": True, "featured": True, "items": ["8 publications par mois", "Planning et programmation", "Rapport mensuel", "Minimum 3 mois"], "cta": "Démarrer"},
            {"name": "Plan Croissance Plus", "price": "[[plan_plus]]", "per": True, "items": ["Réseaux sociaux inclus", "Gestion publicitaire (budget en plus)", "Deux pages SEO par mois", "Entretien trimestriel"], "cta": "Voir le plan", "link": "pricing"},
        ],
        "packages_note": "Tous les prix hors TVA.",
        "faq": [
            (f"Quels réseaux gérez-vous{N}?", "Instagram et Facebook par défaut. LinkedIn ou TikTok sur demande."),
            (f"Dois-je fournir mes propres photos{N}?", "De préférence, oui, les vraies photos fonctionnent le mieux. Si vous n'en avez pas, nous organisons un shooting avec notre photographe partenaire."),
            (f"Pourquoi pas une publication par jour{N}?", "Deux bonnes publications par semaine font plus que sept publications bâclées. La qualité et la régularité l'emportent."),
            (f"Ma page Facebook suffit-elle comme site{N}?", "Mieux vaut pas. En 2026, l'UNIZO a signalé une vague de comptes Meta bloqués. Un site à vous est une base que personne ne peut vous retirer."),
        ],
        "related": ["photo", "ads", "brand"],
    },
    "chatbot": {
        "nav": "Chatbot IA",
        "title": f"Chatbot IA pour votre site{N}: 495{N}€ + 39{N}€/mois | Rozmary",
        "desc": f"Un chatbot IA qui répond jour et nuit sur la base de vos propres textes et tarifs, et transmet les demandes. 495{N}€ de mise en place et 39{N}€ par mois.",
        "h1": "Un chatbot IA qui aide vos clients jour et nuit",
        "lead": "Entraîné sur vos propres textes, tarifs et FAQ. Il répond aux questions, recueille les demandes et vous les transmet.",
        "chips": ["[[bot]] de mise en place", "[[bot_m]] par mois", "Indique qu'il est une IA"],
        "card": "Répond 24h/24 sur la base de vos propres infos.",
        "price_card": "[[bot]]",
        "intro_h": "Moins de questions répétitives, plus de demandes",
        "intro": f"Horaires, prix, délais{N}: beaucoup de questions reviennent chaque semaine. Un chatbot y répond tout de suite, même le soir, et vous transmet les questions difficiles.",
        "bullets": [
            "Réponses basées sur votre propre site et vos documents",
            "Transfert vers WhatsApp, e-mail ou votre agenda",
            "Fonctionne en français, néerlandais et anglais",
            "Indique toujours qu'il s'agit d'un assistant IA, comme l'exige l'AI Act",
            "Aperçu mensuel des questions posées",
        ],
        "packages": [
            {"name": "Chatbot IA", "price": "[[bot]]", "note": "+ [[bot_m]] par mois", "featured": True, "items": ["Mise en place sur vos textes et votre FAQ", "Transfert vers WhatsApp ou e-mail", "Trilingue", "Hébergement, mises à jour et aperçu mensuel"], "cta": "Demander une démo"},
        ],
        "packages_note": "Tous les prix hors TVA.",
        "faq": [
            (f"Un chatbot est-il légal{N}?", "Oui, s'il indique qu'il est une IA. C'est obligatoire depuis le 2 août 2026 en vertu de l'AI Act européen, et nos chatbots le font par défaut."),
            (f"Et si le chatbot ne sait pas répondre{N}?", "Il le dit honnêtement et demande les coordonnées de votre client, pour que vous puissiez le recontacter."),
            (f"Quelles données le chatbot utilise-t-il{N}?", "Uniquement ce que vous fournissez : votre site, vos tarifs et votre FAQ. Les conversations sont conservées selon votre politique de confidentialité."),
            (f"Le chatbot peut-il fixer des rendez-vous{N}?", "Oui, grâce à une connexion avec votre agenda en ligne."),
        ],
        "related": ["software", "website", "pos"],
    },
    "photo": {
        "nav": "Photo & vidéo",
        "title": f"Photographe d'entreprise et vidéo dès 395{N}€ | Rozmary",
        "desc": f"Photos et vidéos professionnelles d'entreprise avec nos photographes partenaires en Campine{N}: demi-journée de shooting dès 395{N}€, images prêtes pour le web.",
        "h1": "Photos et vidéos d'entreprise dès [[photo]]",
        "lead": "De vraies images de vous, de votre équipe et de votre travail. Nous organisons le shooting avec un photographe partenaire et utilisons tout de suite les images sur votre site et vos réseaux.",
        "chips": ["Demi-journée dès [[photo]]", "Partenaires en Campine", "Prêtes pour le web et les réseaux"],
        "card": "De vraies images de vous et de votre travail, via nos partenaires.",
        "price_card": "[[photo]]",
        "intro_h": "Les vraies photos vendent mieux",
        "intro": "Tout le monde reconnaît une photo de banque d'images. Des images de vous, de votre équipe et de votre travail créent la confiance. Nous organisons le shooting et veillons à ce que les photos collent à votre identité et à votre site.",
        "bullets": [
            "Liste de prises de vue basée sur votre site et vos réseaux",
            "Demi-journée de shooting sur place",
            "Photos retouchées pour le web et l'impression",
            "Courtes vidéos pour Instagram et Facebook, sur devis",
            "Images intégrées directement à votre site",
        ],
        "packages": [
            {"name": "Shooting demi-journée", "price": "[[photo]]", "featured": True, "items": ["Préparation et liste de prises de vue", "Demi-journée sur place", "Photos retouchées pour le web et l'impression"], "cta": "Planifier un shooting"},
            {"name": "Vidéo d'entreprise", "price": None, "items": ["Courtes vidéos pour les réseaux sociaux", "Ou un film d'entreprise pour votre site", "Montage et sous-titres"], "cta": "Demander un devis"},
        ],
        "packages_note": "Tous les prix hors TVA.",
        "faq": [
            (f"Qui réalise les photos{N}?", "Un photographe partenaire de la région. Nous nous chargeons de la préparation et veillons au résultat."),
            (f"Puis-je utiliser les photos partout{N}?", f"Oui, pour votre propre communication{N}: site, réseaux sociaux, imprimés et publicités."),
            (f"Est-ce possible en dehors des heures d'ouverture{N}?", "Oui, en concertation. Pour l'horeca et les commerces, nous planifions souvent avant ou après l'ouverture."),
        ],
        "related": ["social", "website", "brand"],
    },
    "pos": {
        "nav": "Caisse, CRM & facturation",
        "title": "Caisse enregistreuse, CRM et facturation Peppol | Rozmary",
        "desc": f"Facturation Peppol obligatoire depuis 2026 : nous configurons votre logiciel de facturation (dès 149{N}€), votre CRM (dès 395{N}€) ou votre caisse (dès 295{N}€).",
        "h1": "Caisse, CRM et facturation : votre administration en digital",
        "lead": "Depuis le 1er janvier 2026, les factures électroniques via Peppol sont obligatoires entre entreprises belges. Nous choisissons avec vous les bons outils et les configurons, reliés à votre site.",
        "chips": ["Prêt pour Peppol", "Conseil indépendant", "Relié à votre site"],
        "card": "Facturation Peppol, CRM et caisse, bien configurés.",
        "price_card": "[[peppol]]",
        "intro_h": "Moins de papier, moins d'erreurs",
        "intro": "Factures, données clients et tickets de caisse doivent se trouver dans des systèmes qui communiquent entre eux. Nous regardons ce dont vous avez besoin, choisissons un outil adapté à votre activité et à votre budget, et le configurons pour vous.",
        "bullets": [
            "Un logiciel de facturation prêt pour Peppol, choisi et configuré",
            "Votre logo, votre numéro de TVA et vos délais de paiement corrects sur chaque facture",
            "Un CRM avec vos clients, devis et suivis",
            "Une caisse pour commerce ou horeca, avec terminal de paiement",
            "Des connexions avec votre site et votre comptable",
        ],
        "packages": [
            {"name": "Démarrage Peppol", "price": "[[peppol]]", "featured": True, "items": ["Choix du logiciel adapté", "Configuration avec vos données et votre logo", "Première facture électronique envoyée ensemble"], "cta": "Démarrer avec Peppol"},
            {"name": "Mise en place CRM", "price": "[[crm]]", "from": True, "items": ["Import de vos clients et contacts", "Devis et suivis configurés", "Connexion avec les formulaires de votre site"], "cta": "Demander une proposition"},
            {"name": "Caisse enregistreuse", "price": "[[pos]]", "from": True, "items": ["Conseil sur la caisse et le terminal", "Encodage des produits et des prix", "Formation pour vous et votre équipe"], "cta": "Demander une proposition"},
        ],
        "packages_note": "Les abonnements logiciels et le matériel sont payés directement au fournisseur. Tous les prix hors TVA.",
        "faq": [
            (f"Dois-je utiliser Peppol{N}?", "Pour les factures à d'autres entreprises belges, la facture électronique structurée via Peppol est la règle depuis le 1er janvier 2026. En cas de doute pour votre situation, vérifiez avec votre comptable."),
            (f"Quel logiciel conseillez-vous{N}?", "Cela dépend de votre activité. Nous choisissons avec vous et votre comptable. Si un fournisseur nous verse une commission, nous vous le disons à l'avance."),
            (f"Vendez-vous aussi des caisses{N}?", "Nous conseillons et configurons votre système. Le matériel et l'abonnement s'achètent directement chez le fournisseur, pour que tout reste à votre nom."),
            (f"Les demandes de mon site peuvent-elles arriver dans mon CRM{N}?", "Oui. Les demandes envoyées via votre site arrivent automatiquement dans votre CRM, avec une notification pour vous."),
        ],
        "related": ["software", "chatbot", "website"],
    },
    "software": {
        "nav": "Logiciels & intégrations",
        "title": "Logiciel sur mesure et intégrations | Rozmary Digital",
        "desc": f"Vous perdez du temps à retaper des données{N}? Nous connectons votre e-shop, fournisseur, CRM et comptabilité, et développons sur mesure dès 1{N}500{N}€.",
        "h1": "Logiciels et intégrations qui vous font gagner du temps",
        "lead": "Retaper, copier et coller, c'est le travail des ordinateurs. Nous connectons vos systèmes et développons ce qui n'existe pas encore.",
        "chips": ["Scan gain de temps gratuit", "Dès [[software]]", "Testé et documenté"],
        "card": "Des intégrations et logiciels sur mesure qui font gagner du temps.",
        "price_card": "[[software]]",
        "intro_h": "Du travail manuel à l'automatique",
        "intro": f"Un fournisseur avec des milliers d'articles, des commandes que vous retapez, des rapports faits à la main chaque mois{N}: tout cela peut être automatique. Nous commençons par un entretien gratuit pour voir où vous perdez le plus de temps.",
        "bullets": [
            "Connexions entre e-shop, fournisseur, CRM et comptabilité",
            "Prix et stock automatiques",
            "Tableaux de bord et rapports",
            "Formulaires et devis qui se suivent tout seuls",
            "Documentation et tests, pour que tout continue à fonctionner",
        ],
        "packages": [
            {"name": "Scan gain de temps", "price": "[[scan]]", "items": ["Entretien de 30 minutes", "Aperçu de ce que vous pouvez automatiser", "Estimation du temps gagné et du coût"], "cta": "Planifier le scan"},
            {"name": "Intégration ou logiciel", "price": "[[software]]", "from": True, "featured": True, "items": ["Analyse et proposition à prix fixe", "Développement et tests", "Documentation", "Maintenance sur demande"], "cta": "Demander une proposition"},
        ],
        "packages_note": "Tous les prix hors TVA.",
        "faq": [
            (f"Qu'avez-vous déjà connecté{N}?", f"Pour Thunder Racing, nous développons une connexion avec un catalogue fournisseur de 27{N}503 articles, avec des règles de prix automatiques pour l'e-shop."),
            (f"Combien coûte un logiciel sur mesure{N}?", "Les petites intégrations démarrent autour de [[software]]. Après le scan gain de temps, vous recevez un prix fixe."),
            (f"Et si quelque chose tombe en panne{N}?", "Chaque intégration a des tests et des alertes. Avec un contrat de maintenance, nous surveillons tout pour vous."),
        ],
        "related": ["pos", "shop", "chatbot"],
    },
}

PRICE_GROUPS = [
    ("Gratuit", None, [
        ("Scan de croissance", "Analyse de votre site, fiche Google, avis et 3 concurrents, plus 15 minutes d'entretien", "scan", False, False, "scan"),
        ("Check publicité", "Trois améliorations pour vos campagnes ou votre projet publicitaire", "scan", False, False, "ads"),
        ("Scan gain de temps", "Que pouvez-vous automatiser, et qu'est-ce que ça rapporte ?", "scan", False, False, "software"),
    ]),
    ("Pour commencer", None, [
        ("Cartes de visite Start", "Design et 250 cartes imprimées, livrées chez vous", "cards", False, False, "cards"),
        ("Carte de visite digitale", "Page de contact avec code QR, plus [[vcard_m]] par mois", "vcard", False, False, "cards"),
        ("Boost fiche Google", "Fiche entièrement configurée, lien d'avis et 50 cartes QR", "gbp", False, False, "google"),
        ("Check légal e-shop", "Bouton de rétractation, garantie, cookies et vie privée vérifiés", "shopcheck", False, False, "shop"),
        ("Démarrage Peppol", "Logiciel de facturation choisi et configuré, première e-facture ensemble", "peppol", False, False, "pos"),
        ("Logo Start", "3 propositions, 2 tours de corrections, tous les fichiers", "logo", False, False, "brand"),
    ]),
    ("Formules", None, [
        ("Identité visuelle", "Logo, couleurs, polices, carte de visite, modèles réseaux sociaux, charte", "brand", False, False, "brand"),
        ("Site Start", "Site one-page avec textes, SEO local, bouton WhatsApp et mesures", "web_start", False, False, "website"),
        ("Pack démarrage", "Identité visuelle, Site Start, Boost fiche Google et 250 cartes ; ou [[starter_m]] par mois", "starter", False, False, "starter"),
        ("Site Croissance", "8 à 15 pages, pages par service et par commune, 2 langues", "web_grow", False, False, "website"),
        ("E-shop Start", "Shopify, 25 produits, Bancontact, check légal inclus", "shop", False, True, "shop"),
    ]),
    ("Plans mensuels", "maandplannen", [
        ("Sérénité", "Hébergement, SSL, sauvegardes, mises à jour et 30 minutes de modifications", "care", True, False, "website"),
        ("Plan Croissance Local", "Sérénité + gestion fiche Google, campagne d'avis, 1 page SEO, rapport mensuel", "plan_local", True, False, "google"),
        ("Plan Croissance Plus", "Plan Croissance Local + 8 publications, gestion publicitaire, 2 pages SEO", "plan_plus", True, False, "ads"),
    ]),
    ("Options", None, [
        ("Gestion publicitaire", "Gestion, tunnel et rapport ; mise en place [[ads_setup]] une fois, budget en plus", "ads_m", True, False, "ads"),
        ("Réseaux sociaux", "8 publications par mois avec planning et rapport", "social_m", True, False, "social"),
        ("Chatbot IA", "Sur vos propres textes, trilingue, conforme à l'AI Act ; plus [[bot_m]] par mois", "bot", False, False, "chatbot"),
        ("Shooting demi-journée", "Avec notre photographe partenaire, photos retouchées pour le web et l'impression", "photo", False, False, "photo"),
        ("Mise en place CRM", "Contacts, devis et suivis, reliés à votre site", "crm", False, True, "pos"),
        ("Caisse enregistreuse", "Conseil, configuration et formation ; matériel en plus", "pos", False, True, "pos"),
        ("Intégration ou logiciel", "Après un scan gain de temps gratuit, à prix fixe", "software", False, True, "software"),
    ]),
]

PAGES = {
    "home": {
        "title": "Rozmary Digital | Partenaire digital des PME en Campine",
        "desc": "Site internet, identité visuelle, fiche Google, publicité et facturation chez un seul partenaire. Prix affichés et site en ligne en 7 jours ouvrables.",
        "eyebrow": "Partenaire digital des indépendants et des PME",
        "h1a": "Plus de clients dans votre région.",
        "h1b": "Un seul partenaire pour tout.",
        "lead": "Site internet, identité visuelle, fiche Google, publicité, réseaux sociaux et votre caisse ou facturation. Nous mettons tout en place, mesurons les résultats et restons votre interlocuteur fixe.",
        "cta2": "Voir tous les tarifs",
        "trust": ["Prix affichés sur le site", "Site en ligne en 7 jours ouvrables", "Français, néerlandais et anglais", "Tout à votre nom"],
        "tickets": [
            ("Site Start", "[[web_start]]", "Site one-page, en ligne en 7 jours ouvrables"),
            ("Pack démarrage", "[[starter]]", "Ou [[starter_m]] par mois, sans acompte"),
            ("Plan Croissance Local", "[[plan_local]]/mois", "Plus d'avis, plus visible, rapport mensuel"),
        ],
        "services_h": "Tout pour votre entreprise, sous un même toit",
        "services_p": "Choisissez un service ou confiez-nous l'ensemble. Chaque service affiche son prix, hors TVA.",
        "starter_h": "Vous démarrez ? Tout est réglé en une fois.",
        "starter_p": "Le Pack démarrage vous donne un logo et une identité visuelle, 250 cartes de visite, un site internet et une fiche Google prête pour vos premiers avis.",
        "starter_items": ["Logo et identité visuelle", "250 cartes de visite", "Site Start", "Fiche Google configurée"],
        "starter_price_note": "ou [[starter_m]] par mois, sans acompte",
        "starter_cta": "Voir le Pack démarrage",
        "method_h": "Le marketing en cinq étapes, sans jargon",
        "method_p": "Chaque service que nous vendons correspond à l'une de ces étapes. Vous savez donc toujours pourquoi vous investissez.",
        "method_loop": "Chaque mois, nous mesurons ce qui fonctionne et nous ajustons.",
        "method_cta": "Découvrir notre méthode",
        "work_h": "Réalisations récentes en Campine",
        "work_cta": "Toutes les réalisations",
        "why_h": "Pourquoi Rozmary",
        "why": [
            ("Prix affichés", "Vous savez à l'avance ce que ça coûte. Pas de ‘demandez un devis’ pour chaque détail."),
            ("Un seul interlocuteur", "De la carte de visite à l'e-shop : une personne qui connaît votre entreprise et suit tout."),
            ("Rapide, sans bâcler", "Nous travaillons avec des outils d'IA. Chaque texte, chaque design et chaque ligne de code est vérifié par nous."),
            ("Local et joignable", "Basés en Campine, joignables par WhatsApp, et nous passons volontiers chez vous."),
            ("Mesurable", "Chaque site compte les appels, les messages WhatsApp et les demandes. Vous recevez un rapport mensuel clair."),
            ("Tout à votre nom", "Nom de domaine, textes et comptes restent à vous. Vous pouvez arrêter à tout moment."),
        ],
        "plans_h": "Après le lancement : un plan mensuel",
        "plans_p": "Un site que personne n'entretient perd du terrain. Nos plans mensuels vous gardent visible, sûr et à jour.",
        "plans": [
            ("Sérénité", "care", ["Hébergement et SSL", "Sauvegardes et mises à jour", "30 minutes de modifications par mois"]),
            ("Plan Croissance Local", "plan_local", ["Tout Sérénité", "Gestion de la fiche Google et campagne d'avis", "Une nouvelle page SEO par mois", "Rapport mensuel"]),
            ("Plan Croissance Plus", "plan_plus", ["Tout Plan Croissance Local", "8 publications par mois", "Gestion publicitaire (budget en plus)", "Entretien trimestriel"]),
        ],
        "plans_cta": "Comparer tous les tarifs",
        "faq": [
            (f"Combien coûte un site chez Rozmary{N}?", "Un site one-page coûte [[web_start]] hors TVA, un site de 8 à 15 pages [[web_grow]]. Vous préférez ne pas payer d'acompte ? Choisissez le Pack démarrage à [[starter_m]] par mois."),
            (f"ChatGPT ne peut-il pas simplement créer mon site{N}?", f"L'IA peut monter une première version, et nous l'utilisons aussi. La différence se fait ensuite{N}: les bons mots-clés, une technique rapide, des textes justes, des mesures et quelqu'un qui intervient si quelque chose ne va pas."),
            (f"En combien de temps mon site est-il en ligne{N}?", "Un site one-page est en ligne dans les 7 jours ouvrables après réception de votre logo, de vos textes et de vos photos. Sinon, vous recevez [[late_discount]] de réduction."),
            (f"Suis-je lié par un long contrat{N}?", "Non. Les plans mensuels durent au moins 3 mois, puis sont résiliables chaque mois. Votre nom de domaine et votre site restent à vous."),
            (f"Travaillez-vous aussi en dehors de la Campine{N}?", "Oui. Nous travaillons dans toute la Flandre, à Bruxelles et en Wallonie, en français, en néerlandais ou en anglais. En Campine, nous passons volontiers chez vous."),
        ],
    },
    "pricing": {
        "title": "Tarifs site internet, logo et marketing 2026 | Rozmary",
        "desc": f"Tous les tarifs de Rozmary Digital sur une page{N}: site dès 995{N}€, logo dès 249{N}€, cartes de visite 119{N}€, plans mensuels dès 29{N}€. Hors TVA, sans surprise.",
        "h1": "Tous les tarifs, simplement",
        "lead": f"Pas de ‘demandez un devis’ pour chaque détail. Voici ce que tout coûte, hors TVA. Vous hésitez{N}? Le scan de croissance est gratuit.",
        "col_product": "Produit", "col_what": "Contenu", "col_price": "Prix",
        "rules_h": "Conditions",
        "rules": [
            "Tous les prix sont hors TVA.",
            f"Projets{N}: acompte de 50{N}%, le solde à la livraison.",
            f"Plans mensuels{N}: minimum 3 mois, puis résiliables chaque mois, par domiciliation.",
            f"Pack démarrage par mois{N}: 24 mois, ensuite seule la formule Sérénité continue.",
            f"Garantie{N}: en ligne dans les 7 jours ouvrables après réception de vos éléments, sinon [[late_discount]] de réduction. Deux tours de corrections inclus.",
        ],
        "faq": [
            (f"Pourquoi vos prix sont-ils en ligne{N}?", "Parce qu'en tant qu'entrepreneur, vous voulez savoir où vous en êtes. Et parce que cela nous fait gagner du temps, que nous préférons consacrer à votre projet."),
            (f"Y a-t-il des coûts cachés{N}?", "Non. Seulement ce que vous payez directement à des tiers, comme votre nom de domaine, Shopify, votre budget publicitaire ou des abonnements logiciels. Nous le disons toujours à l'avance."),
            (f"Puis-je obtenir une réduction{N}?", "Le Pack démarrage est 20 % moins cher que ses éléments séparés. Pour le reste, nous appliquons le même prix pour tous."),
        ],
    },
    "method": {
        "title": "Notre méthode : le marketing en 5 étapes | Rozmary",
        "desc": "De la vision au client fidèle : voici comment nous abordons le marketing pour les indépendants. Cinq étapes sans jargon, mesurées et ajustées chaque mois.",
        "h1": "Le marketing en cinq étapes, sans jargon",
        "lead": "Le marketing n'a rien de mystérieux. Ce sont cinq étapes qui se suivent. Nous regardons où votre entreprise perd des clients et nous commençons par là.",
        "loop_h": "Mesurer et ajuster chaque mois",
        "loop_p": f"Chaque mois, vous recevez un court rapport{N}: combien de personnes vous ont trouvé, appelé, envoyé un WhatsApp ou fait une demande, et combien de nouveaux avis vous avez reçus. Sur cette base, nous choisissons l'étape suivante.",
        "project_h": "Déroulement d'un projet",
    },
    "work": {
        "title": "Réalisations : sites et marketing en Campine | Rozmary",
        "desc": f"Nos réalisations pour Shiny Cleaning et Thunder Racing à Geel{N}: sites SEO locaux, identité visuelle, gestion de stock et connexion e-shop de 27{N}503 articles.",
        "h1": "Réalisations",
        "lead": "Deux entreprises locales, deux questions différentes. Voici comment nous les avons abordées.",
        "visit": "Voir le site",
        "cases": {
            "shiny": {
                "sector": "Laveur de vitres et entreprise de nettoyage",
                "question": "Un site d'une seule page que presque personne ne trouvait, sans prix, et donc peu de demandes.",
                "did": ["Positionnement comme spécialiste de l'extérieur en Campine", "Recherche de mots-clés : ‘ruitenwasser’ est cherché 1,75 fois plus que ‘glazenwasser’", "Dix pages de services et dix-sept pages de communes avec un texte local propre", "Une page de tarifs, WhatsApp comme premier bouton et une page d'accueil en NL, FR et EN"],
                "facts": [("34", "pages"), ("17", "communes"), ("3", "langues")],
            },
            "thunder": {
                "sector": "Garage et magasin de scooters",
                "question": "Un audit de croissance a révélé des points faibles : tout tenait sur une seule page, sans stock ni prix visibles.",
                "did": ["Audit de croissance du site, des avis et des concurrents", "Nouveau site de 26 pages par service, marque et commune", "Page de gestion pour mettre à jour soi-même stock, prix et avis", "Connexion avec le catalogue du fournisseur PePe Parts pour l'e-shop, en développement"],
                "facts": [("26", "pages"), (f"27{N}503", "articles connectés"), ("59", "tests automatisés")],
            },
        },
    },
    "about": {
        "title": "À propos de Rozmary Digital : partenaire digital en Campine",
        "desc": "Rozmary Digital est une agence digitale pour indépendants et PME. Un seul interlocuteur, des prix fixes et des outils d'IA, toujours contrôlés par un humain.",
        "h1": "Un seul partenaire pour tout ce qui est digital",
        "lead": "Rozmary Digital aide les indépendants et les petites entreprises à trouver plus de clients, avec des sites, une identité visuelle, du marketing et les outils qui vont avec.",
        "sections": [
            ("Qui nous sommes", "Derrière Rozmary Digital, il y a Sebastiaan, formé en gestion d'entreprise et en informatique. Il est votre interlocuteur fixe : il écoute votre activité, veille à la qualité et suit tout. Pour la photo, la vidéo et l'impression, nous travaillons avec des partenaires fixes de la région."),
            ("Comment nous utilisons l'IA", "Nous utilisons des outils d'IA pour la recherche, les textes, le design et le code. Nous livrons ainsi plus vite et à meilleur prix. Chaque texte, chaque design et chaque ligne de code est vérifié par un humain avant d'être mis en ligne."),
            ("D'où vient le nom", "Rozmary fait référence au romarin : une plante qui pousse toute l'année, qui est robuste et reste verte. Elle symbolise depuis toujours le souvenir. Exactement ce que fait un bon partenaire."),
        ],
        "values_h": "Ce que vous pouvez attendre de nous",
        "values": ["Des prix fixés à l'avance", "Un seul interlocuteur, joignable par WhatsApp", "Nom de domaine, textes et comptes à votre nom", "Pas de longs contrats", "Des conseils honnêtes, même quand c'est ‘pas encore nécessaire’"],
        "area_h": "Où nous travaillons",
        "area_p": "Notre base est en Campine, où nous passons volontiers chez vous. En ligne, nous travaillons pour toute la Flandre, Bruxelles et la Wallonie, en français, en néerlandais et en anglais.",
    },
    "contact": {
        "title": "Nous contacter | Rozmary Digital",
        "desc": "Envoyez-nous un WhatsApp, un e-mail ou remplissez le formulaire. Réponse sous un jour ouvrable, et en Campine, nous passons volontiers chez vous.",
        "h1": "Contact",
        "lead": "Une question, une idée ou envie de démarrer tout de suite ? Envoyez un message, nous répondons dans un délai d'un jour ouvrable.",
        "wa_h": "WhatsApp", "wa_p": "Le plus rapide. Envoyez un message et nous répondons au plus vite.",
        "mail_h": "E-mail", "mail_p": "Vous préférez l'e-mail ? C'est toujours possible.",
        "form_h": "Ou remplissez le formulaire",
        "visit_h": "Rencontre", "visit_p": "En Campine, nous passons volontiers chez vous pour faire connaissance.",
    },
    "scan": {
        "title": "Scan de croissance gratuit pour votre site | Rozmary",
        "desc": "Demandez un scan de croissance gratuit : nous analysons votre site, votre fiche Google, vos avis et trois concurrents, et en parlons en 15 minutes.",
        "h1": "Scan de croissance gratuit : où perdez-vous des clients ?",
        "lead": "Nous analysons votre site, votre fiche Google, vos avis et trois concurrents. Lors d'un entretien de 15 minutes, vous recevez les trois améliorations les plus importantes. Gratuit et sans engagement.",
        "check_h": "Ce que nous analysons",
        "checks": ["Vitesse et utilisation sur smartphone", "Visibilité sur vos principaux mots-clés", "Votre fiche Google et vos avis", "La facilité avec laquelle un visiteur vous contacte", "Votre position face à trois concurrents", "Ce qu'il faut améliorer en premier"],
        "form_h": "Demandez votre scan",
        "no_site": "Pas encore de site ? Nous analysons alors votre fiche Google, vos réseaux sociaux et vos concurrents.",
    },
    "privacy": {
        "title": "Politique de confidentialité | Rozmary Digital",
        "desc": "Comment Rozmary Digital traite vos données : quelles données nous recevons via les formulaires, pourquoi, combien de temps nous les gardons et quels sont vos droits.",
        "h1": "Politique de confidentialité",
        "lead": "En bref : nous utilisons vos données uniquement pour vous aider et vous répondre.",
        "sections": [
            ("Qui est responsable ?", "Rozmary Digital, [[legal]], est responsable du traitement de vos données personnelles. Vos questions peuvent être envoyées à [[email]]."),
            ("Quelles données ?", "Ce que vous remplissez dans un formulaire ou envoyez par WhatsApp ou e-mail : votre nom, votre entreprise, votre adresse e-mail, votre numéro de téléphone, votre site, votre commune et votre message."),
            ("Pourquoi ?", "Pour répondre à votre question, réaliser un scan ou une proposition et, si vous devenez client, exécuter notre contrat et vous facturer."),
            ("Combien de temps ?", "Les demandes qui ne deviennent pas une mission sont supprimées après 12 mois. Les données clients sont conservées aussi longtemps que la loi l'exige, par exemple 10 ans pour les factures."),
            ("Cookies", "Ce site n'utilise pas de cookies de suivi ou publicitaires. Uniquement ce qui est strictement nécessaire à son fonctionnement."),
            ("Avec qui partageons-nous ?", "Uniquement avec les prestataires dont nous avons besoin pour travailler, comme notre hébergeur (Hostinger) et notre messagerie. Nous ne vendons jamais vos données."),
            ("Vos droits", "Vous pouvez toujours consulter, faire corriger ou faire supprimer vos données. Envoyez un e-mail à [[email]]. Si vous n'êtes pas satisfait, vous pouvez vous adresser à l'Autorité de protection des données (autoriteprotectiondonnees.be)."),
        ],
    },
    "thanks": {
        "title": "Merci | Rozmary Digital",
        "desc": "Merci pour votre message à Rozmary Digital. Nous répondons dans un délai d'un jour ouvrable.",
        "h1": "Merci, nous avons bien reçu votre message",
        "lead": "Nous répondons dans un délai d'un jour ouvrable. C'est urgent ? Envoyez-nous directement un WhatsApp.",
        "back": "Retour à l'accueil",
    },
    "404": {
        "title": "Page introuvable | Rozmary Digital",
        "h1": "Cette page n'existe pas (ou plus)",
        "lead": "Vous trouverez peut-être ce que vous cherchez ici :",
    },
}

MODEL = [
    ("Vision", "Pour qui êtes-vous le meilleur choix ?", "Nous définissons votre public, votre offre et vos prix. Chacun sait ainsi pourquoi il devrait vous choisir.", ["starter", "brand"]),
    ("Visibilité", "Vous trouve-t-on là où vos clients cherchent ?", "Google, votre fiche Google, la publicité et les réseaux sociaux : nous vous rendons visible au moment où quelqu'un cherche.", ["google", "ads", "social"]),
    ("Confiance", "Pourquoi vous choisir ?", "Un site, des avis, de vraies photos et des exemples qui montrent pourquoi on vous choisit plutôt que le voisin.", ["website", "photo", "cards"]),
    ("Conversion", "Un visiteur devient-il client ?", "WhatsApp, devis, rendez-vous ou paiement en ligne, avec un suivi automatique. Plus aucune demande perdue.", ["shop", "chatbot", "pos"]),
    ("Fidélisation", "Le client revient-il et en amène-t-il d'autres ?", "Demander des avis, une newsletter et la maintenance. Un client fidèle coûte moins cher qu'un nouveau.", ["software", "social"]),
]
