"""Nederlandse inhoud. Prijzen via [[sleutel]] (zie siteconf.py)."""

UI = {
    "skip": "Naar de inhoud",
    "menu": "Menu", "close": "Sluiten",
    "nav_services": "Diensten", "nav_pricing": "Prijzen", "nav_method": "Werkwijze",
    "nav_work": "Realisaties", "nav_about": "Over ons", "nav_contact": "Contact",
    "cta_scan": "Gratis Groeiscan", "whatsapp": "WhatsApp", "whatsapp_long": "Stuur een WhatsApp",
    "from": "vanaf", "per_month": "/maand", "per_month_long": "per maand", "excl": "excl. btw",
    "free": "gratis", "on_quote": "op offerte", "more": "Meer info", "home": "Home",
    "packages_h": "Pakketten en prijzen", "steps_h": "Zo werkt het", "faq_h": "Veelgestelde vragen",
    "related_h": "Ook interessant", "all_services": "Alle diensten", "all_prices": "Alle prijzen",
    "footer_services": "Diensten", "footer_company": "Rozmary", "footer_contact": "Contact",
    "footer_area": "Werkgebied", "footer_tagline": "Digitale partner voor starters en kmo's.",
    "kbo": "KBO/btw", "kbo_missing": "Ondernemingsnummer volgt", "privacy": "Privacy",
    "rights": "Alle prijzen excl. btw.", "lang_label": "Taal",
    "cta_band_h": "Benieuwd waar jouw zaak klanten laat liggen?",
    "cta_band_p": "Vraag een gratis Groeiscan. We bekijken je website, Google-profiel, reviews en drie concurrenten, en bespreken het in 15 minuten.",
    "breadcrumb": "Kruimelpad",
    "wa_general": "Hallo Rozmary Digital, ik heb een vraag.",
    "wa_service": "Hallo Rozmary Digital, ik heb een vraag over {s}.",
    "region": "Kempen", "recommended": "Aanrader",
    "form": {
        "name": "Naam", "company": "Bedrijf (optioneel)", "email": "E-mail",
        "phone": "Telefoon (optioneel)", "website": "Website (als je er een hebt)",
        "city": "Gemeente", "interest": "Waarmee kunnen we helpen?", "other": "Iets anders",
        "message": "Je bericht", "consent": "Rozmary Digital mag mijn gegevens gebruiken om me te contacteren.",
        "consent_link": "Privacy", "submit": "Verstuur", "sending": "Bezig met versturen…",
        "ok": "Bedankt! We antwoorden binnen één werkdag.",
        "fail": "Versturen lukte niet. Stuur je bericht via WhatsApp of mail ons.",
        "wa_fallback": "Verstuur via WhatsApp", "required": "Verplicht veld",
        "wa_intro": "Hallo Rozmary Digital, ",
    },
}

STEPS = [
    ("Kennismaking", "In 15 minuten bespreken we je zaak, je doel en je budget."),
    ("Voorstel met vaste prijs", "Je krijgt een duidelijk voorstel. Akkoord? Dan betaal je 50% voorschot."),
    ("Wij bouwen, jij keurt", "Je volgt alles mee en krijgt twee correctierondes."),
    ("Live en opvolging", "We lanceren, meten wat het oplevert en stellen een maandplan voor als dat zinvol is."),
]

SERVICES = {
    "website": {
        "nav": "Website",
        "title": "Website laten maken vanaf €995 | Rozmary Digital",
        "desc": "Website laten maken in de Kempen: one-pager vanaf €995, bedrijfssite vanaf €2.495. Teksten, lokale SEO, WhatsApp-knop en meting inbegrepen.",
        "h1": "Website laten maken vanaf [[web_start]]",
        "lead": "Een snelle, vindbare website die bezoekers omzet in aanvragen. Teksten, lokale SEO, WhatsApp-knop en meting zitten erin.",
        "chips": ["Live in 7 werkdagen", "Teksten inbegrepen", "Domein op jouw naam"],
        "card": "Snelle, vindbare site met teksten en WhatsApp-knop.",
        "price_card": "[[web_start]]",
        "intro_h": "Een website die voor je werkt",
        "intro": "De meeste kleine ondernemers hebben geen mooiere website nodig, maar een die gevonden wordt en aanvragen oplevert. Daarom bouwen we elke site rond de zoektermen van je klanten en één duidelijke actie.",
        "bullets": [
            "Teksten op basis van wat je klanten echt googelen",
            "Pagina's per dienst en per gemeente als je dat wil",
            "WhatsApp-, bel- en offerteknoppen op elke pagina",
            "Meting van telefoons, berichten en aanvragen",
            "Technisch in orde: snel, mobiel, veilig en met correcte Google-gegevens",
        ],
        "packages": [
            {"name": "Website Start", "price": "[[web_start]]", "items": ["One-pager met tot 6 secties", "Teksten en zoekwoorden inbegrepen", "WhatsApp-, bel- en offerteknop", "Google-basisinstellingen en meting", "Live in 7 werkdagen"], "cta": "Start mijn website"},
            {"name": "Website Groei", "price": "[[web_grow]]", "featured": True, "items": ["8 tot 15 pagina's", "Pagina per dienst en per gemeente", "Twee talen naar keuze", "Blog of nieuwssectie", "Prijzen- en FAQ-pagina"], "cta": "Vraag een voorstel"},
            {"name": "Starterspakket", "price": "[[starter]]", "note": "of [[starter_m]] per maand", "items": ["Website Start", "Logo en huisstijl", "250 visitekaartjes", "Google-profiel ingericht"], "cta": "Bekijk het pakket", "link": "starter"},
        ],
        "packages_note": "Hosting en onderhoud: Zorgeloos voor [[care]] per maand. Alle prijzen excl. btw.",
        "faq": [
            ("Wat kost het om een website te laten maken?", "Bij ons betaal je [[web_start]] voor een one-pager en [[web_grow]] voor een site met 8 tot 15 pagina's, excl. btw. In België liggen de prijzen tussen €550 bij een freelancer en €7.000 of meer bij grotere bureaus."),
            ("Kan ik een website per maand betalen?", "Ja. Met het Starterspakket betaal je [[starter_m]] per maand gedurende 24 maanden, zonder voorschot. Hosting en onderhoud zitten erin."),
            ("Kan ChatGPT een website maken?", "Het kan een ruwe versie maken. Wat ontbreekt, is de rest: zoekwoordonderzoek, snelle hosting, correcte Google-gegevens, meting en iemand die je site onderhoudt. Dat doen wij, en we gebruiken AI om het sneller en betaalbaarder te maken."),
            ("Van wie is de website als hij klaar is?", "Van jou. Het domein staat op jouw naam en je krijgt alle bestanden. Stop je met ons onderhoud, dan helpen we je verhuizen."),
        ],
        "related": ["starter", "google", "brand"],
    },
    "starter": {
        "nav": "Starterspakket",
        "title": "Starterspakket voor zelfstandigen: €1.495 | Rozmary",
        "desc": "Net gestart als zelfstandige? Logo, huisstijl, 250 visitekaartjes, website en Google-profiel in één pakket: €1.495, of €99 per maand zonder voorschot.",
        "h1": "Starterspakket: alles om te starten voor [[starter]]",
        "lead": "Logo, huisstijl, visitekaartjes, website en Google-profiel in één keer. Ook per maand te betalen, zonder voorschot.",
        "chips": ["Of [[starter_m]] per maand", "Klaar in 3 weken", "Eén aanspreekpunt"],
        "card": "Logo, visitekaartjes, website en Google-profiel in één pakket.",
        "price_card": "[[starter]]",
        "intro_h": "Je eerste indruk, meteen goed",
        "intro": "Als starter heb je al genoeg aan je hoofd. Met het Starterspakket staat je zaak in één keer professioneel online en op papier, zonder vijf verschillende leveranciers.",
        "bullets": [
            "Logo en huisstijl: kleuren, lettertypes en een mini-merkgids",
            "250 gedrukte visitekaartjes, thuis geleverd",
            "Website Start: one-pager met teksten en WhatsApp-knop",
            "Google-profiel ingericht, met reviewlink en QR-kaartjes",
            "Bij betalen per maand: hosting en onderhoud inbegrepen",
        ],
        "packages": [
            {"name": "In één keer", "price": "[[starter]]", "featured": True, "items": ["Logo en huisstijl", "250 visitekaartjes", "Website Start", "Google Profiel Boost"], "cta": "Start met het pakket"},
            {"name": "Per maand", "price": "[[starter_m]]", "per": True, "items": ["Hetzelfde pakket, zonder voorschot", "Hosting en onderhoud inbegrepen", "24 maanden, daarna Zorgeloos aan [[care]] per maand", "Domein op jouw naam"], "cta": "Kies betalen per maand"},
        ],
        "packages_note": "Los gekocht kost dit samen [[starter_loose]]. Alle prijzen excl. btw.",
        "steps": [
            ("Kennismaking", "In 15 minuten bespreken we je zaak, je klanten en je stijl."),
            ("Huisstijl (week 1)", "Je krijgt drie logovoorstellen en twee correctierondes."),
            ("Website en drukwerk (week 2)", "We bouwen je site en bestellen je visitekaartjes."),
            ("Live en vindbaar (week 3)", "Je site gaat online en je Google-profiel staat klaar voor je eerste reviews."),
        ],
        "faq": [
            ("Wat zit er precies in het Starterspakket?", "Een logo met huisstijl en mini-merkgids, 250 gedrukte visitekaartjes, een one-page website met teksten en WhatsApp-knop, en een volledig ingericht Google-profiel met reviewlink en QR-kaartjes."),
            ("Kan ik het pakket per maand betalen?", "Ja, [[starter_m]] per maand gedurende 24 maanden, zonder voorschot. Hosting en onderhoud zitten erin."),
            ("Ik heb al een logo. Kan ik het pakket aanpassen?", "Zeker. Dan ruilen we de huisstijl in voor iets wat je wel nodig hebt, zoals extra pagina's of drukwerk."),
            ("Hoe lang duurt het?", "Gemiddeld drie weken, afhankelijk van hoe snel je feedback geeft."),
        ],
        "related": ["website", "brand", "cards"],
    },
    "brand": {
        "nav": "Huisstijl & logo",
        "title": "Logo laten maken vanaf €249 | Huisstijl | Rozmary",
        "desc": "Logo laten maken of een volledige huisstijl: logo vanaf €249, huisstijl met visitekaartje en social-templates voor €595. Vaste prijs, alle bestanden.",
        "h1": "Logo en huisstijl laten maken, vanaf [[logo]]",
        "lead": "Een herkenbaar logo en een huisstijl die overal hetzelfde oogt: op je gevel, je website, je bestelwagen en Instagram.",
        "chips": ["3 voorstellen", "2 correctierondes", "Alle bestanden"],
        "card": "Herkenbaar logo en een huisstijl die overal klopt.",
        "price_card": "[[logo]]",
        "intro_h": "Meer dan een logo",
        "intro": "Een logo maak je vandaag in vijf minuten met een app. Een huisstijl die jouw klanten aanspreekt en op elk formaat werkt, is iets anders. Die bouwen we samen met je op.",
        "bullets": [
            "Logo in kleur, zwart-wit en als icoon",
            "Kleurenpalet en lettertypes",
            "Visitekaartje en e-mailhandtekening",
            "Templates voor Instagram en Facebook",
            "Mini-merkgids, zodat iedereen je stijl juist gebruikt",
        ],
        "packages": [
            {"name": "Logo Start", "price": "[[logo]]", "items": ["3 logovoorstellen", "2 correctierondes", "Bestanden voor web en druk (SVG, PNG, PDF)"], "cta": "Bestel Logo Start"},
            {"name": "Huisstijl", "price": "[[brand]]", "featured": True, "items": ["Alles uit Logo Start", "Kleuren en lettertypes", "Ontwerp van je visitekaartje", "Templates voor social media", "Mini-merkgids"], "cta": "Start mijn huisstijl"},
        ],
        "packages_note": "Alle prijzen excl. btw. Na betaling zijn alle rechten van jou.",
        "faq": [
            ("Wat kost het laten maken van een logo?", "Bij ons [[logo]] voor Logo Start en [[brand]] voor een volledige huisstijl, excl. btw. Online zie je prijzen van €99 tot €279 voor enkel een logo."),
            ("Kan ChatGPT een logo maken?", "AI-tools maken snel een beeldmerk, maar vaak zonder uniek karakter, zonder bruikbare bestanden en zonder zekerheid over de rechten. Wij gebruiken AI voor snelle schetsen en werken het logo daarna zelf uit."),
            ("Waar kan je gratis een logo maken?", "Met tools zoals Canva, en voor een eerste test is dat prima. Wil je een logo dat op elk formaat scherp blijft en bij je klanten past, dan loont een ontwerp op maat."),
            ("Van wie zijn de rechten?", "Na betaling zijn alle rechten op het logo en de huisstijl van jou."),
        ],
        "related": ["cards", "starter", "social"],
    },
    "cards": {
        "nav": "Visitekaartjes",
        "title": "Visitekaartjes laten maken: ontwerp + druk €119 | Rozmary",
        "desc": "Visitekaartjes laten ontwerpen én drukken: 250 kaartjes in je huisstijl voor €119, thuis geleverd. Of een digitaal visitekaartje met QR-code voor €79.",
        "h1": "Visitekaartjes laten maken: ontwerp en druk voor [[cards]]",
        "lead": "Je ontwerpt niets zelf en bestelt niets zelf. Wij maken het ontwerp in je huisstijl en laten 250 kaartjes drukken en leveren.",
        "chips": ["250 kaartjes inbegrepen", "Thuis geleverd", "Ook digitaal"],
        "card": "Ontwerp en druk van 250 kaartjes, of een digitaal kaartje.",
        "price_card": "[[cards]]",
        "intro_h": "Kaartjes die bij je zaak passen",
        "intro": "Een online drukker is goedkoop, maar dan ontwerp je zelf. Wij zorgen dat je kaartje klopt met je logo, je site en je gevel, en dat alles op de juiste plek staat.",
        "bullets": [
            "Dubbelzijdig ontwerp in je huisstijl",
            "Controle van alle gegevens en een drukklaar bestand",
            "250 kaartjes op stevig papier, thuis geleverd",
            "Extra: een digitaal visitekaartje met QR-code",
        ],
        "packages": [
            {"name": "Visitekaartjes Start", "price": "[[cards]]", "featured": True, "items": ["Ontwerp in je huisstijl", "250 gedrukte kaartjes", "Levering in België"], "cta": "Bestel je kaartjes"},
            {"name": "Digitaal visitekaartje", "price": "[[vcard]]", "note": "+ [[vcard_m]] per maand", "items": ["Eigen contactpagina met je gegevens", "QR-code voor je kaartje of gevel", "Knop om je contact op te slaan", "Wijzigingen inbegrepen"], "cta": "Bestel digitaal"},
        ],
        "packages_note": "Alle prijzen excl. btw.",
        "faq": [
            ("Kan ik ook enkel het ontwerp bestellen?", "Ja, dan krijg je een drukklaar bestand. Vraag het via WhatsApp of het contactformulier."),
            ("Hoe lang duurt het?", "Na je akkoord op het ontwerp liggen je kaartjes meestal binnen een week in de bus."),
            ("Wat is een digitaal visitekaartje?", "Een eigen webpagina met je gegevens, knoppen om te bellen of te mailen en een knop om je contact op te slaan. Via een QR-code deel je het in een seconde."),
            ("Ik heb nog geen logo. Wat nu?", "Dan starten we met Logo Start of met het Starterspakket, waar 250 kaartjes al in zitten."),
        ],
        "related": ["brand", "starter", "google"],
    },
    "google": {
        "nav": "Google-profiel",
        "title": "Google Bedrijfsprofiel optimaliseren: €149 | Rozmary",
        "desc": "Hoger in Google Maps in je eigen gemeente: we richten je Google Bedrijfsprofiel volledig in voor €149, met reviewlink en QR-kaartjes. Daarna ook maandelijks.",
        "h1": "Google Bedrijfsprofiel optimaliseren voor [[gbp]]",
        "lead": "Wie in je gemeente zoekt, ziet eerst de kaart met drie bedrijven. Wij zorgen dat jij daar staat, met foto's, diensten en reviews die overtuigen.",
        "chips": ["Profiel volledig ingericht", "Reviewlink en QR-kaartjes", "Lokale zoekwoorden"],
        "card": "Beter gevonden in Google Maps, met meer reviews.",
        "price_card": "[[gbp]]",
        "intro_h": "De kaart wint de klik",
        "intro": "Bij een zoekopdracht als ‘kapper Geel’ staan drie bedrijven op de kaart, boven alle andere resultaten. Daar beslissen reviews, volledigheid en activiteit. Precies wat we voor je regelen.",
        "bullets": [
            "Categorieën, diensten, openingsuren en werkgebied juist ingesteld",
            "Tien foto's en een beschrijving met je zoekwoorden",
            "Een eigen reviewlink plus 50 QR-kaartjes",
            "Koppeling met je website en meting van klikken",
            "Tips om elke week zichtbaar te blijven",
        ],
        "packages": [
            {"name": "Google Profiel Boost", "price": "[[gbp]]", "featured": True, "items": ["Profiel volledig ingericht", "Reviewlink en 50 QR-kaartjes", "Lokale zoekwoorden in je beschrijving"], "cta": "Boost mijn profiel"},
            {"name": "Groeiplan Lokaal", "price": "[[plan_local]]", "per": True, "items": ["Twee berichten per week op je profiel", "Reviewcampagne via WhatsApp en e-mail", "Eén nieuwe SEO-pagina per maand", "Hosting, onderhoud en maandrapport"], "cta": "Start het Groeiplan"},
        ],
        "packages_note": "Alle prijzen excl. btw. Groeiplannen: minimum 3 maanden, daarna maandelijks opzegbaar.",
        "faq": [
            ("Hoe kom ik hoger in Google Maps?", "Met een volledig profiel, de juiste categorie, regelmatige updates en vooral veel recente, echte reviews. In de Kempen heeft de top-3 in veel sectoren minder dan 50 reviews, dus dat is haalbaar."),
            ("Schrijven jullie reviews voor mij?", "Nee. Nepreviews zijn verboden en schaden je. We maken het je klanten wel heel makkelijk om er één achter te laten."),
            ("Ik heb geen winkel. Kan ik toch een profiel hebben?", "Ja. Als dienstverlener aan huis stel je een werkgebied in en verberg je je adres."),
            ("Ik heb al een profiel. Wat doen jullie dan?", "We nemen het over, vullen aan wat ontbreekt en ruimen fouten op."),
        ],
        "related": ["website", "ads", "social"],
    },
    "shop": {
        "nav": "Webshop",
        "title": "Webshop laten maken vanaf €2.995 | Rozmary Digital",
        "desc": "Webshop laten maken met Shopify: vanaf €2.995 voor 25 producten, met Bancontact en de wettelijke verplichtingen van 2026. Of eerst een wetcheck voor €149.",
        "h1": "Webshop laten maken vanaf [[shop]]",
        "lead": "Een Shopify-webshop die je zelf beheert, met Bancontact, verzending en de nieuwe wettelijke verplichtingen van 2026 in orde.",
        "chips": ["Shopify", "Bancontact en kaart", "Wettelijk in orde"],
        "card": "Shopify-webshop met Bancontact, klaar voor de regels van 2026.",
        "price_card": "[[shopcheck]]",
        "intro_h": "Verkopen zonder kopzorgen",
        "intro": "Een webshop is meer dan producten online zetten. Betalen, verzenden, retours en regels moeten kloppen. Sinds juni 2026 moet elke webshop bijvoorbeeld een duidelijke herroepingsknop tonen.",
        "bullets": [
            "Shopify-shop in je huisstijl",
            "25 producten ingevoerd, met foto's en teksten",
            "Betalen met Bancontact en kaart",
            "Verzendzones, btw en retours ingesteld",
            "Herroepingsknop, garantie-info en voorwaarden volgens de regels van 2026",
        ],
        "packages": [
            {"name": "Webshop-wetcheck", "price": "[[shopcheck]]", "items": ["Herroepingsknop en herroepingsformulier", "Garantie-informatie en groene claims", "Cookies, privacy en voorwaarden", "Actielijst met prioriteiten"], "cta": "Check mijn webshop"},
            {"name": "Webshop Start", "price": "[[shop]]", "from": True, "featured": True, "items": ["Shopify-shop in je huisstijl", "25 producten ingevoerd", "Bancontact, verzending en btw ingesteld", "Wetcheck inbegrepen", "Opleiding van een uur"], "cta": "Vraag een voorstel"},
        ],
        "packages_note": "Het Shopify-abonnement betaal je zelf aan Shopify. Alle prijzen excl. btw.",
        "faq": [
            ("Wat kost het om een webshop te laten maken?", "Bij ons vanaf [[shop]] excl. btw voor een Shopify-shop met 25 producten. In België lopen de prijzen van €1.250 tot €25.000 of meer, afhankelijk van maatwerk en koppelingen. Daarbovenop betaal je Shopify, vanaf ongeveer €24 per maand."),
            ("Waarom Shopify?", "Het is betrouwbaar en veilig, en je beheert het zelf zonder technische kennis. Voor grote catalogi of speciale koppelingen bouwen we op maat."),
            ("Welke regels gelden in 2026 voor webshops?", "Sinds 19 juni 2026 moet je een duidelijke herroepingsknop hebben, en sinds 27 september 2026 gelden nieuwe regels voor garantie-informatie en groene claims. Onze wetcheck zet alles voor je op een rij."),
            ("Shopify of RozmaryPOS?", "Verkoop je enkel online, dan is Shopify meestal de eenvoudigste keuze. Heb je ook een winkel, dan is RozmaryPOS vaak beter: kassa en webshop delen één voorraad."),
            ("Kunnen jullie mijn leverancier koppelen?", "Ja. Voor Thunder Racing bouwen we een koppeling met de catalogus van een leverancier, met automatische prijzen en voorraad."),
        ],
        "related": ["pos", "ads", "photo"],
    },
    "ads": {
        "nav": "Adverteren & funnels",
        "title": "Google Ads en Meta-advertenties uitbesteden | Rozmary",
        "desc": "Adverteren op Google, Facebook en Instagram met een salesfunnel die aanvragen oplevert. Beheer vanaf €199 per maand plus je budget. Eerst een gratis check.",
        "h1": "Online adverteren en salesfunnels",
        "lead": "Advertenties op Google, Facebook en Instagram, gekoppeld aan een landingspagina en automatische opvolging. Je ziet elke maand wat ze opleveren.",
        "chips": ["Beheer vanaf [[ads_m]] per maand", "Budget apart en transparant", "Maandrapport"],
        "card": "Advertenties met een funnel die aanvragen oplevert.",
        "price_card": "[[ads_m]]", "price_card_per": True,
        "intro_h": "Een klik is nog geen klant",
        "intro": "Klikken zijn duur: voor ‘website laten maken’ betaal je in België al snel €13 per klik. Daarom adverteren we pas als de landingspagina klaar is om te converteren, en volgen we elke aanvraag automatisch op.",
        "bullets": [
            "Campagnes op Google Zoeken, Google Maps, Facebook en Instagram",
            "Een landingspagina per campagne, met één duidelijke actie",
            "Automatische opvolging via e-mail of WhatsApp",
            "Meting van aanvragen, niet alleen van klikken",
            "Een maandrapport in gewone taal",
        ],
        "packages": [
            {"name": "Advertentie-check", "price": "[[scan]]", "items": ["We bekijken je campagnes of je plan", "Drie concrete verbeterpunten", "Gesprek van 15 minuten"], "cta": "Vraag de check aan"},
            {"name": "Advertentiebeheer", "price": "[[ads_m]]", "per": True, "featured": True, "items": ["Opzet van je campagnes: [[ads_setup]] eenmalig", "Beheer en optimalisatie", "Salesfunnel met opvolgmails", "Maandrapport", "Minimum 3 maanden"], "cta": "Start met adverteren"},
        ],
        "packages_note": "Je advertentiebudget betaal je rechtstreeks aan Google of Meta. Alle prijzen excl. btw.",
        "faq": [
            ("Hoeveel budget heb ik nodig?", "Voor lokale campagnes raden we minstens €300 per maand aan. Minder kan, maar dan duurt het langer voor je betrouwbare resultaten ziet."),
            ("Wat is een salesfunnel?", "Het pad van eerste klik tot klant: advertentie, landingspagina, aanvraag en opvolging. Wij bouwen en meten elk stuk."),
            ("Beloven jullie meer omzet?", "Nee. Niemand kan dat eerlijk beloven. We beloven wel dat je elke maand ziet wat je advertenties opleveren en wat we bijsturen."),
            ("Waarom niet gewoon zelf boosten op Facebook?", "Boosten levert vooral likes op. Een campagne met een doel, een doelgroep en meting levert aanvragen op."),
        ],
        "related": ["website", "social", "google"],
    },
    "social": {
        "nav": "Social media",
        "title": "Social media uitbesteden vanaf €349 per maand | Rozmary",
        "desc": "Social media uitbesteden: acht posts per maand voor Instagram en Facebook in je huisstijl, met planning en rapport, voor €349 per maand.",
        "h1": "Social media uitbesteden vanaf [[social_m]] per maand",
        "lead": "Acht doordachte posts per maand voor Instagram en Facebook, in je huisstijl en ingepland. Jij keurt goed, wij doen de rest.",
        "chips": ["8 posts per maand", "Jij keurt goed", "Maandrapport"],
        "card": "Acht posts per maand in je huisstijl, ingepland.",
        "price_card": "[[social_m]]", "price_card_per": True,
        "intro_h": "Zichtbaar blijven, zonder stress",
        "intro": "Social media werkt als je regelmatig post en je klanten iets bijbrengt. Dat lukt zelden naast je eigenlijke werk. Wij maken een maandplanning, schrijven de posts en plannen ze in.",
        "bullets": [
            "Maandplanning afgestemd op je seizoen en je acties",
            "Acht posts met tekst en beeld in je huisstijl",
            "Inplannen op Instagram en Facebook",
            "Maandrapport met bereik en berichten",
            "Foto- of videoshoot via onze partner, als je wil",
        ],
        "packages": [
            {"name": "Social media", "price": "[[social_m]]", "per": True, "featured": True, "items": ["8 posts per maand", "Planning en inplannen", "Maandrapport", "Minimum 3 maanden"], "cta": "Start met social media"},
            {"name": "Groeiplan Plus", "price": "[[plan_plus]]", "per": True, "items": ["Social media inbegrepen", "Advertentiebeheer (budget apart)", "Twee SEO-pagina's per maand", "Kwartaalgesprek"], "cta": "Bekijk Groeiplan Plus", "link": "pricing"},
        ],
        "packages_note": "Alle prijzen excl. btw.",
        "faq": [
            ("Welke kanalen doen jullie?", "Standaard Instagram en Facebook. LinkedIn of TikTok op vraag."),
            ("Moet ik zelf foto's aanleveren?", "Liefst wel, echte foto's werken het best. Heb je er geen, dan plannen we een shoot met onze partnerfotograaf."),
            ("Waarom geen dagelijkse posts?", "Twee goede posts per week doen meer dan zeven haastige. Kwaliteit en regelmaat winnen."),
            ("Is mijn Facebook-pagina genoeg als website?", "Liever niet. UNIZO meldde in 2026 een golf van geblokkeerde Meta-accounts. Een eigen website is een fundament dat niemand je kan afnemen."),
        ],
        "related": ["photo", "ads", "brand"],
    },
    "chatbot": {
        "nav": "AI-chatbot",
        "title": "AI-chatbot voor je website: €495 + €39/maand | Rozmary",
        "desc": "Een AI-chatbot die dag en nacht vragen beantwoordt op basis van je eigen teksten en prijzen, en aanvragen doorstuurt. €495 opstart en €39 per maand.",
        "h1": "Een AI-chatbot die je klanten dag en nacht helpt",
        "lead": "Getraind op je eigen teksten, prijzen en FAQ. Hij beantwoordt vragen, verzamelt aanvragen en stuurt ze naar jou door.",
        "chips": ["[[bot]] opstart", "[[bot_m]] per maand", "Meldt dat hij AI is"],
        "card": "Beantwoordt vragen 24/7 op basis van je eigen info.",
        "price_card": "[[bot]]",
        "intro_h": "Minder dezelfde vragen, meer aanvragen",
        "intro": "Openingsuren, prijzen, levertijden: veel vragen komen elke week terug. Een chatbot beantwoordt ze meteen, ook 's avonds, en geeft moeilijke vragen door aan jou.",
        "bullets": [
            "Antwoorden op basis van je eigen website en documenten",
            "Doorsturen naar WhatsApp, e-mail of je agenda",
            "Werkt in het Nederlands, Frans en Engels",
            "Meldt altijd dat het om een AI-assistent gaat, zoals de AI Act vraagt",
            "Maandelijks overzicht van de gestelde vragen",
        ],
        "packages": [
            {"name": "AI-chatbot", "price": "[[bot]]", "note": "+ [[bot_m]] per maand", "featured": True, "items": ["Opzet op je eigen teksten en FAQ", "Doorsturen naar WhatsApp of e-mail", "Drietalig", "Hosting, updates en maandoverzicht"], "cta": "Vraag een demo"},
        ],
        "packages_note": "Alle prijzen excl. btw.",
        "faq": [
            ("Is een chatbot wettelijk in orde?", "Ja, als hij meldt dat hij een AI is. Dat is sinds 2 augustus 2026 verplicht onder de Europese AI Act, en onze bots doen dat standaard."),
            ("Wat als de bot een vraag niet kan beantwoorden?", "Dan zegt hij dat eerlijk en vraagt hij de contactgegevens van je klant, zodat jij kan opvolgen."),
            ("Welke gegevens gebruikt de bot?", "Enkel wat jij aanlevert: je website, prijzen en FAQ. Gesprekken bewaren we volgens je privacybeleid."),
            ("Kan de bot afspraken inplannen?", "Ja, met een koppeling naar je online agenda."),
        ],
        "related": ["software", "website", "pos"],
    },
    "photo": {
        "nav": "Foto & video",
        "title": "Bedrijfsfotograaf en bedrijfsvideo vanaf €395 | Rozmary",
        "desc": "Bedrijfsfoto's en video's via onze partnerfotografen in de Kempen: halve dag fotoshoot vanaf €395. Wij plannen, jij krijgt beelden voor site en social.",
        "h1": "Bedrijfsfoto's en video vanaf [[photo]]",
        "lead": "Echte beelden van jou, je team en je werk. Wij plannen de shoot met een partnerfotograaf en zetten de beelden meteen aan het werk op je site en socials.",
        "chips": ["Halve dag vanaf [[photo]]", "Partners in de Kempen", "Klaar voor web en social"],
        "card": "Echte beelden van jou en je werk, via onze partners.",
        "price_card": "[[photo]]",
        "intro_h": "Echte foto's verkopen beter",
        "intro": "Stockfoto's herkent iedereen. Beelden van jou, je team en je werk bouwen vertrouwen. Wij regelen de shoot en zorgen dat de foto's passen bij je huisstijl en je website.",
        "bullets": [
            "Shotlist op basis van je website en socials",
            "Halve dag fotoshoot op locatie",
            "Bewerkte foto's voor web en druk",
            "Korte video's voor Instagram en Facebook, op offerte",
            "Beelden meteen verwerkt op je site",
        ],
        "packages": [
            {"name": "Fotoshoot halve dag", "price": "[[photo]]", "featured": True, "items": ["Voorbereiding en shotlist", "Halve dag op locatie", "Bewerkte foto's voor web en druk"], "cta": "Plan een shoot"},
            {"name": "Bedrijfsvideo", "price": None, "items": ["Korte video's voor social media", "Of een bedrijfsfilm voor je site", "Montage en ondertiteling"], "cta": "Vraag een offerte"},
        ],
        "packages_note": "Alle prijzen excl. btw.",
        "faq": [
            ("Wie maakt de foto's?", "Een vaste partnerfotograaf uit de regio. Wij doen de voorbereiding en bewaken het resultaat."),
            ("Mag ik de foto's overal gebruiken?", "Ja, voor je eigen communicatie: site, socials, drukwerk en advertenties."),
            ("Kan het ook buiten de openingsuren?", "In overleg, ja. Voor horeca en winkels plannen we vaak voor of na de openingsuren."),
        ],
        "related": ["social", "website", "brand"],
    },
    "pos": {
        "nav": "Kassa & webshop",
        "title": "RozmaryPOS: kassasysteem + webshop vanaf €175/maand",
        "desc": "RozmaryPOS is ons eigen kassasysteem met webshop: één dashboard, één voorraad en Mollie-betalingen in de winkel en online. Vanaf €175 per maand.",
        "h1": "RozmaryPOS: kassa en webshop in één systeem",
        "lead": "Ons eigen kassasysteem met geïntegreerde webshop. Je verkoopt in de winkel en online vanuit één dashboard, met één voorraad en betalingen via Mollie.",
        "chips": ["Kassa [[pos_m]] per maand", "Met webshop [[pos_shop_m]] per maand", "Mollie-terminal gekoppeld"],
        "card": "Eigen kassa en webshop in één systeem, met één voorraad.",
        "price_card": "[[pos_m]]", "price_card_per": True,
        "intro_h": "Winkel en webshop, één voorraad",
        "intro": "Verkoop je in de winkel én online, dan houd je vaak twee systemen bij en loopt je voorraad scheef. RozmaryPOS brengt alles samen: een verkoop aan de kassa haalt het stuk meteen uit je webshop, en een online bestelling verschijnt meteen aan de kassa.",
        "bullets": [
            "Eén dashboard voor verkoop, voorraad, klanten en bestellingen",
            "Volledige kassa: scannen, bonprinter, dagafsluiting en voorraadbeheer",
            "Webshop met categorieën, promoties en winkelwagen; bestellingen komen meteen binnen",
            "Betalen via Mollie, online en aan de kassa met een gekoppelde terminal",
            "Winstmarge en btw per product automatisch berekend, met rapporten",
            "Koppeling met je groothandel of leverancier via API",
            "In de cloud, met SSL-beveiliging en dagelijkse back-ups",
        ],
        "packages": [
            {"name": "RozmaryPOS Kassa", "price": "[[pos_m]]", "per": True, "items": ["Kassasysteem voor één vestiging", "Product- en voorraadbeheer", "Rapporten over omzet, marge en btw", "Support en updates"], "cta": "Vraag een demo"},
            {"name": "Kassa + Webshop", "price": "[[pos_shop_m]]", "per": True, "featured": True, "items": ["Alles uit RozmaryPOS Kassa", "Webshop met hosting en online beheer", "Online betalen via Mollie", "Eén voorraad voor winkel en webshop"], "cta": "Vraag een demo"},
            {"name": "Peppol-start", "price": "[[peppol]]", "items": ["Facturatieprogramma kiezen en instellen", "Je logo en btw-gegevens op elke factuur", "Eerste e-factuur samen versturen"], "cta": "Start met Peppol"},
            {"name": "CRM inrichten", "price": "[[crm]]", "from": True, "items": ["Klanten en contacten importeren", "Offertes en opvolging instellen", "Koppeling met je websiteformulieren"], "cta": "Vraag een voorstel"},
        ],
        "packages_note": "RozmaryPOS: eenmalige opstart van [[pos_setup_min]] à [[pos_setup_max]] voor installatie, instellingen op maat (zoals je leverancier koppelen of je catalogus importeren) en opleiding. Looptijd 36 maanden, betaald via domiciliëring. Mollie-transactiekosten en hardware apart. Alle prijzen excl. btw.",
        "steps": [
            ("Demo", "We tonen je RozmaryPOS, met jouw soort producten als voorbeeld."),
            ("Voorstel", "Je krijgt een voorstel met de opstartkost en je maandprijs."),
            ("Installatie en koppelingen", "We zetten je catalogus erin en koppelen je leverancier en de Mollie-terminal."),
            ("Opleiding en start", "Jij en je team leren werken met de kassa, en we volgen de eerste weken op."),
        ],
        "faq": [
            ("Wat is RozmaryPOS?", "Ons eigen kassasysteem met geïntegreerde webshop, vergelijkbaar met Shopify maar zelf ontwikkeld. Daardoor kunnen we het aanpassen aan jouw zaak, bijvoorbeeld met een koppeling met je leverancier."),
            ("Hoe betalen mijn klanten?", "Online via Mollie met Bancontact, kaart en andere methodes. In de winkel met een Mollie-terminal die aan de kassa gekoppeld is, zodat elke kaartbetaling automatisch in de kassa staat."),
            ("Kan ik mijn leverancier koppelen?", "Ja, via een API-koppeling. Voor Thunder Racing bouwen we zo een koppeling met een catalogus van 27.503 artikels, met prijzen en voorraad die automatisch up-to-date blijven."),
            ("Hoe lang loopt het contract?", "RozmaryPOS loopt 36 maanden en wordt maandelijks via domiciliëring betaald. Websites en maandplannen hebben kortere looptijden."),
            ("Is RozmaryPOS geschikt voor horeca?", "RozmaryPOS is gemaakt voor winkels. Moet je zaak een geregistreerd kassasysteem (witte kassa) gebruiken, zoals in de horeca, dan bekijken we samen welk gecertificeerd systeem je nodig hebt."),
            ("Moet ik Peppol gebruiken?", "Voor facturen aan andere Belgische ondernemingen is een e-factuur via Peppol sinds 1 januari 2026 de regel. Twijfel je of het voor jou geldt, check het dan met je boekhouder."),
        ],
        "related": ["shop", "software", "website"],
    },
    "software": {
        "nav": "Software & koppelingen",
        "title": "Software op maat en koppelingen | Rozmary Digital",
        "desc": "Tijd verliezen met overtypen? Wij koppelen je webshop, leverancier, CRM en boekhouding, en bouwen software op maat vanaf €1.500. Eerst een gratis tijdwinstscan.",
        "h1": "Software en koppelingen die je tijd teruggeven",
        "lead": "Overtypen, kopiëren en plakken laten we computers doen. Wij koppelen je systemen en bouwen wat er nog niet bestaat.",
        "chips": ["Tijdwinstscan gratis", "Vanaf [[software]]", "Getest en gedocumenteerd"],
        "card": "Koppelingen en software op maat die tijd besparen.",
        "price_card": "[[software]]",
        "intro_h": "Van handwerk naar automatisch",
        "intro": "Een leverancier met duizenden artikels, bestellingen die je overtypt, rapporten die je elke maand met de hand maakt: dat kan automatisch. We starten met een gratis gesprek om te zien waar de meeste tijd zit.",
        "bullets": [
            "Koppelingen tussen webshop, leverancier, CRM en boekhouding",
            "Automatische prijzen en voorraad",
            "Dashboards en rapporten",
            "Formulieren en offertes die zichzelf opvolgen",
            "Documentatie en tests, zodat het blijft werken",
        ],
        "packages": [
            {"name": "Tijdwinstscan", "price": "[[scan]]", "items": ["Gesprek van 30 minuten", "Overzicht van wat je kan automatiseren", "Schatting van tijdwinst en kostprijs"], "cta": "Plan de scan"},
            {"name": "Koppeling of software", "price": "[[software]]", "from": True, "featured": True, "items": ["Analyse en voorstel met vaste prijs", "Bouw en tests", "Documentatie", "Onderhoud op afspraak"], "cta": "Vraag een voorstel"},
        ],
        "packages_note": "Alle prijzen excl. btw.",
        "faq": [
            ("Wat hebben jullie al gekoppeld?", "Voor Thunder Racing bouwen we een koppeling met een leverancierscatalogus van 27.503 artikels, met automatische prijsregels voor de webshop."),
            ("Wat kost software op maat?", "Kleine koppelingen starten rond [[software]]. Na de tijdwinstscan krijg je een vaste prijs."),
            ("Wat als er iets misloopt?", "Elke koppeling heeft tests en meldingen. Met een onderhoudscontract volgen we alles voor je op."),
        ],
        "related": ["pos", "shop", "chatbot"],
    },
}

# Productlijst voor de prijzenpagina: sleutel -> (naam, korte omschrijving, prijssleutel, per maand?, vanaf?, dienst)
PRICE_GROUPS = [
    ("Gratis", None, [
        ("Groeiscan", "Check van je website, Google-profiel, reviews en 3 concurrenten, plus 15 minuten gesprek", "scan", False, False, "scan"),
        ("Advertentie-check", "Drie verbeterpunten voor je campagnes of je advertentieplan", "scan", False, False, "ads"),
        ("Tijdwinstscan", "Wat kan je automatiseren, en wat levert het op?", "scan", False, False, "software"),
    ]),
    ("Instap", None, [
        ("Visitekaartjes Start", "Ontwerp plus 250 gedrukte kaartjes, thuis geleverd", "cards", False, False, "cards"),
        ("Digitaal visitekaartje", "Contactpagina met QR-code, plus [[vcard_m]] per maand", "vcard", False, False, "cards"),
        ("Google Profiel Boost", "Profiel volledig ingericht, reviewlink en 50 QR-kaartjes", "gbp", False, False, "google"),
        ("Webshop-wetcheck", "Herroepingsknop, garantie-info, cookies en privacy nagekeken", "shopcheck", False, False, "shop"),
        ("Peppol-start", "Facturatieprogramma gekozen en ingesteld, eerste e-factuur samen", "peppol", False, False, "pos"),
        ("Logo Start", "3 voorstellen, 2 correctierondes, alle bestanden", "logo", False, False, "brand"),
    ]),
    ("Pakketten", None, [
        ("Huisstijl", "Logo, kleuren, lettertypes, visitekaartje, social-templates, merkgids", "brand", False, False, "brand"),
        ("Website Start", "One-pager met teksten, lokale SEO, WhatsApp-knop en meting", "web_start", False, False, "website"),
        ("Starterspakket", "Huisstijl, Website Start, Google Profiel Boost en 250 kaartjes; of [[starter_m]] per maand", "starter", False, False, "starter"),
        ("Website Groei", "8 tot 15 pagina's, dienst- en gemeentepagina's, 2 talen", "web_grow", False, False, "website"),
        ("Webshop Start", "Shopify, 25 producten, Bancontact, wetcheck inbegrepen", "shop", False, True, "shop"),
    ]),
    ("Maandplannen", "maandplannen", [
        ("Zorgeloos", "Hosting, SSL, back-ups, updates en 30 minuten wijzigingen", "care", True, False, "website"),
        ("Groeiplan Lokaal", "Zorgeloos + Google-profielbeheer, reviewcampagne, 1 SEO-pagina, maandrapport", "plan_local", True, False, "google"),
        ("Groeiplan Plus", "Groeiplan Lokaal + 8 socialmediaposts, advertentiebeheer, 2 SEO-pagina's", "plan_plus", True, False, "ads"),
    ]),
    ("Extra's", None, [
        ("Advertentiebeheer", "Beheer, funnel en rapport; opzet [[ads_setup]] eenmalig, budget apart", "ads_m", True, False, "ads"),
        ("Social media", "8 posts per maand met planning en rapport", "social_m", True, False, "social"),
        ("AI-chatbot", "Op je eigen teksten, drietalig, AI Act-conform; plus [[bot_m]] per maand", "bot", False, False, "chatbot"),
        ("Fotoshoot halve dag", "Via onze partnerfotograaf, bewerkte foto's voor web en druk", "photo", False, False, "photo"),
        ("CRM inrichten", "Contacten, offertes en opvolging, gekoppeld aan je site", "crm", False, True, "pos"),
        ("RozmaryPOS Kassa", "Kassasysteem voor één vestiging, met voorraad en rapporten; opstart [[pos_setup_min]] à [[pos_setup_max]]", "pos_m", True, False, "pos"),
        ("RozmaryPOS Kassa + Webshop", "Kassa en webshop met één voorraad en Mollie-betalingen", "pos_shop_m", True, False, "pos"),
        ("Koppeling of software", "Na een gratis tijdwinstscan, met vaste prijs", "software", False, True, "software"),
    ]),
]

PAGES = {
    "home": {
        "title": "Rozmary Digital | Digitale partner voor kmo's in de Kempen",
        "desc": "Website, huisstijl, Google-profiel, advertenties en facturatie bij één partner uit de Kempen. Vaste prijzen op de site en een website live in 7 werkdagen.",
        "eyebrow": "Digitale partner voor starters en kmo's",
        "h1a": "Meer klanten uit je eigen regio.",
        "h1b": "Eén partner die alles regelt.",
        "lead": "Website, huisstijl, Google-profiel, advertenties, social media en je kassa of facturatie. Wij zetten het op, meten wat het oplevert en blijven je vaste aanspreekpunt.",
        "cta2": "Bekijk alle prijzen",
        "trust": ["Prijzen gewoon op de site", "Website live in 7 werkdagen", "Nederlands, Frans en Engels", "Alles op jouw naam"],
        "tickets": [
            ("Website Start", "[[web_start]]", "One-pager, live in 7 werkdagen"),
            ("Starterspakket", "[[starter]]", "Of [[starter_m]] per maand, zonder voorschot"),
            ("Groeiplan Lokaal", "[[plan_local]]/maand", "Meer reviews, beter gevonden, maandrapport"),
        ],
        "services_h": "Alles voor je zaak, onder één dak",
        "services_p": "Kies één dienst of laat ons het geheel regelen. Bij elke dienst staat de prijs, excl. btw.",
        "starter_h": "Net gestart? Alles in één keer geregeld.",
        "starter_p": "Het Starterspakket geeft je een logo en huisstijl, 250 visitekaartjes, een website en een Google-profiel dat klaar is voor je eerste reviews.",
        "starter_items": ["Logo en huisstijl", "250 visitekaartjes", "Website Start", "Google-profiel ingericht"],
        "starter_price_note": "of [[starter_m]] per maand, zonder voorschot",
        "starter_cta": "Bekijk het Starterspakket",
        "method_h": "Marketing in vijf stappen, zonder jargon",
        "method_p": "Elke dienst die we verkopen, hoort bij één van deze stappen. Zo weet je altijd waarom je ergens in investeert.",
        "method_loop": "Elke maand meten we wat werkt en sturen we bij.",
        "method_cta": "Lees hoe we werken",
        "work_h": "Recent werk uit de Kempen",
        "work_cta": "Alle realisaties",
        "why_h": "Waarom Rozmary",
        "why": [
            ("Prijzen op de site", "Je weet vooraf wat het kost. Geen ‘vraag een offerte’ voor elke kleinigheid."),
            ("Eén aanspreekpunt", "Van visitekaartje tot webshop: één persoon die je zaak kent en alles opvolgt."),
            ("Snel, zonder te raffelen", "We werken met slimme AI-tools. Elke tekst, elk ontwerp en elke lijn code controleren we zelf."),
            ("Lokaal en bereikbaar", "Uit de Kempen, bereikbaar via WhatsApp, en we komen gerust langs."),
            ("Meetbaar", "Elke site telt telefoons, WhatsApp-berichten en aanvragen. Je krijgt een helder maandrapport."),
            ("Alles op jouw naam", "Domein, teksten en accounts blijven van jou, ook als je stopt."),
        ],
        "plans_h": "Na de lancering: een vast maandplan",
        "plans_p": "Een site die niemand onderhoudt, verliest terrein. Onze maandplannen houden je vindbaar, veilig en up-to-date.",
        "plans": [
            ("Zorgeloos", "care", ["Hosting en SSL", "Back-ups en updates", "30 minuten wijzigingen per maand"]),
            ("Groeiplan Lokaal", "plan_local", ["Alles uit Zorgeloos", "Google-profielbeheer en reviewcampagne", "Eén nieuwe SEO-pagina per maand", "Maandrapport"]),
            ("Groeiplan Plus", "plan_plus", ["Alles uit Groeiplan Lokaal", "8 socialmediaposts per maand", "Advertentiebeheer (budget apart)", "Kwartaalgesprek"]),
        ],
        "plans_cta": "Vergelijk alle prijzen",
        "faq": [
            ("Wat kost een website laten maken bij Rozmary?", "Een one-page website kost [[web_start]] excl. btw, een site met 8 tot 15 pagina's [[web_grow]]. Liever geen voorschot? Neem het Starterspakket voor [[starter_m]] per maand."),
            ("Kan ChatGPT mijn website niet gewoon maken?", "AI kan een eerste versie in elkaar zetten, en wij gebruiken het ook. Het verschil zit in wat erna komt: de juiste zoektermen, snelle techniek, teksten die kloppen, meting en iemand die het opvolgt als er iets misloopt."),
            ("Hoe snel staat mijn site online?", "Een one-pager staat live binnen 7 werkdagen nadat we je logo, teksten en foto's hebben. Lukt dat niet, dan krijg je [[late_discount]] korting."),
            ("Zit ik vast aan een lang contract?", "Voor websites en maandplannen niet: minimum 3 maanden, daarna maandelijks opzegbaar. Alleen RozmaryPOS loopt 36 maanden, omdat installatie en koppelingen erin zitten. Je domein en je site blijven altijd van jou."),
            ("Werken jullie ook buiten de Kempen?", "Ja. We werken in heel Vlaanderen, Brussel en Wallonië, in het Nederlands, Frans of Engels. In de Kempen komen we graag langs."),
        ],
    },
    "pricing": {
        "title": "Prijzen website, logo en marketing 2026 | Rozmary",
        "desc": "Alle prijzen van Rozmary Digital op één pagina: website vanaf €995, logo vanaf €249, visitekaartjes €119, maandplannen vanaf €29. Excl. btw.",
        "h1": "Alle prijzen, gewoon op een rij",
        "lead": "Geen ‘vraag een offerte’ voor elke kleinigheid. Hieronder staat wat alles kost, excl. btw. Twijfel je? De Groeiscan is gratis.",
        "col_product": "Product", "col_what": "Wat je krijgt", "col_price": "Prijs",
        "rules_h": "Spelregels",
        "rules": [
            "Alle prijzen zijn excl. btw.",
            "Projecten: 50% voorschot, de rest bij oplevering.",
            "Maandplannen: minimum 3 maanden, daarna maandelijks opzegbaar, via domiciliëring.",
            "Starterspakket per maand: 24 maanden, daarna loopt enkel Zorgeloos door.",
            "RozmaryPOS: opstart [[pos_setup_min]] à [[pos_setup_max]], looptijd 36 maanden via domiciliëring.",
            "Garantie: live binnen 7 werkdagen na je input, of [[late_discount]] korting. Twee correctierondes inbegrepen.",
        ],
        "faq": [
            ("Waarom staan jullie prijzen online?", "Omdat je als ondernemer wil weten waar je aan toe bent. En omdat het ons tijd bespaart die we liever in je project steken."),
            ("Zijn er verborgen kosten?", "Nee. Enkel wat je zelf rechtstreeks aan derden betaalt, zoals je domeinnaam, Shopify, advertentiebudget of software-abonnementen. Dat zeggen we altijd vooraf."),
            ("Krijg ik korting?", "Het Starterspakket is 20% goedkoper dan de onderdelen apart. Verder hanteren we één prijs voor iedereen."),
        ],
    },
    "method": {
        "title": "Hoe we werken: marketing in 5 stappen | Rozmary",
        "desc": "Van visie tot vaste klant: zo pakken we marketing aan voor kleine ondernemers. Vijf stappen zonder jargon, en elke maand meten en bijsturen.",
        "h1": "Marketing in vijf stappen, zonder jargon",
        "lead": "Marketing is geen mysterie. Het zijn vijf stappen die elkaar opvolgen. Wij bekijken waar jouw zaak klanten laat liggen en beginnen daar.",
        "loop_h": "Elke maand meten en bijsturen",
        "loop_p": "Elke maand krijg je een kort rapport: hoeveel mensen je vonden, belden, een WhatsApp stuurden of een aanvraag deden, en hoeveel nieuwe reviews je kreeg. Op basis daarvan kiezen we de volgende stap.",
        "project_h": "Zo verloopt een project",
    },
    "work": {
        "title": "Realisaties: websites en marketing in de Kempen | Rozmary",
        "desc": "Ons werk voor Shiny Cleaning en Thunder Racing uit Geel: lokale SEO-websites, huisstijl, een eigen reviewsysteem en een webshopkoppeling met 27.503 artikels.",
        "h1": "Realisaties",
        "lead": "Twee lokale bedrijven, twee verschillende vragen. Zo pakten we het aan.",
        "visit": "Bekijk de site",
        "cases": {
            "shiny": {
                "sector": "Glazenwasser en schoonmaakbedrijf",
                "question": "Een site van één pagina die bijna niemand vond, zonder prijzen, en dus weinig aanvragen.",
                "did": ["Positionering als buitenspecialist van de Kempen", "Zoekwoordonderzoek: ‘ruitenwasser’ wordt 1,75 keer vaker gezocht dan ‘glazenwasser’", "Tien dienstpagina's en zeventien gemeentepagina's met eigen lokale tekst", "Een prijzenpagina, WhatsApp als eerste knop en een homepage in NL, FR en EN"],
                "facts": [("34", "pagina's"), ("17", "gemeenten"), ("3", "talen")],
            },
            "thunder": {
                "sector": "Scootergarage en winkel",
                "question": "Een groeiaudit bracht knelpunten aan het licht: alles stond op één pagina en er was geen voorraad of prijs te zien.",
                "did": ["Groeiaudit van site, reviews en concurrenten", "Nieuwe site met meer dan 50 pagina's per dienst, merk, gemeente en gids", "Eigen reviewsysteem dat de Google-reviews automatisch op de site toont", "RozmaryPOS, onze kassa met webshop, gekoppeld aan de catalogus van leverancier PePe Parts: in ontwikkeling"],
                "facts": [("50+", "pagina's"), ("4", "talen"), ("27.503", "artikels via API")],
            },
        },
    },
    "about": {
        "title": "Over Rozmary Digital: digitale partner uit de Kempen",
        "desc": "Rozmary Digital is een digitaal bureau voor starters en kmo's. Eén aanspreekpunt, vaste prijzen en slimme AI-tools, altijd gecontroleerd door een mens.",
        "h1": "Eén partner voor alles wat digitaal is",
        "lead": "Rozmary Digital helpt starters en kleine ondernemers aan meer klanten, met websites, huisstijl, marketing en de tools erachter.",
        "sections": [
            ("Wie we zijn", "Achter Rozmary Digital staat Sebastiaan, opgeleid in bedrijfsmanagement en IT. Hij is je vaste aanspreekpunt: hij luistert naar je zaak, bewaakt de kwaliteit en volgt alles op. Voor foto, video en drukwerk werken we met vaste partners uit de regio."),
            ("Hoe we AI gebruiken", "We werken met slimme AI-tools voor onderzoek, teksten, ontwerp en code. Zo leveren we sneller en betaalbaarder. Elke tekst, elk ontwerp en elke regel code wordt nagekeken door een mens voor hij bij jou online komt."),
            ("Waar de naam vandaan komt", "Rozmary verwijst naar rozemarijn: een plant die het hele jaar groeit, taai is en groen blijft. Ze staat van oudsher voor ‘niet vergeten’. Precies wat een goede partner doet."),
        ],
        "values_h": "Wat je van ons mag verwachten",
        "values": ["Prijzen die vooraf vastliggen", "Eén aanspreekpunt, bereikbaar via WhatsApp", "Domein, teksten en accounts op jouw naam", "Korte looptijden voor websites en maandplannen", "Eerlijk advies, ook als dat ‘nog niet nodig’ is"],
        "area_h": "Waar we werken",
        "area_p": "Onze thuisbasis is de Kempen. Daar komen we graag langs. Online werken we voor heel Vlaanderen, Brussel en Wallonië, in het Nederlands, Frans en Engels.",
    },
    "contact": {
        "title": "Contact opnemen | Rozmary Digital",
        "desc": "Stuur ons een WhatsApp-bericht, mail ons of vul het formulier in. We antwoorden op werkdagen binnen één werkdag, en in de Kempen komen we graag langs.",
        "h1": "Contact",
        "lead": "Een vraag, een idee of meteen van start? Stuur een bericht, we antwoorden binnen één werkdag.",
        "wa_h": "WhatsApp", "wa_p": "De snelste weg. Stuur een bericht en we antwoorden zo snel mogelijk.",
        "mail_h": "E-mail", "mail_p": "Liever mailen? Dat kan altijd.",
        "form_h": "Of vul het formulier in",
        "visit_h": "Langskomen", "visit_p": "In de Kempen komen we graag bij je langs voor een kennismaking.",
        "company_h": "Bedrijfsgegevens", "company_p": "Rozmary Digital is een handelsnaam van [[legal]], eenmanszaak.",
    },
    "scan": {
        "title": "Gratis Groeiscan voor je website en Google-profiel | Rozmary",
        "desc": "Vraag een gratis Groeiscan: we checken je website, Google-profiel, reviews en drie concurrenten, en bespreken in 15 minuten waar je klanten laat liggen.",
        "h1": "Gratis Groeiscan: waar laat je zaak klanten liggen?",
        "lead": "We bekijken je website, je Google-profiel, je reviews en drie concurrenten. In een gesprek van 15 minuten krijg je de drie belangrijkste verbeterpunten. Gratis en zonder verplichting.",
        "check_h": "Wat we bekijken",
        "checks": ["Snelheid en gebruik op gsm", "Vindbaarheid op je belangrijkste zoektermen", "Je Google-profiel en je reviews", "Hoe makkelijk een bezoeker contact opneemt", "Hoe je scoort tegenover drie concurrenten", "Wat je als eerste moet aanpakken"],
        "form_h": "Vraag je Groeiscan aan",
        "no_site": "Nog geen website? Dan bekijken we je Google-profiel, je socials en je concurrenten.",
    },
    "privacy": {
        "title": "Privacybeleid | Rozmary Digital",
        "desc": "Hoe Rozmary Digital omgaat met je gegevens: welke gegevens we via formulieren ontvangen, waarom, hoe lang we ze bewaren en welke rechten je hebt.",
        "h1": "Privacybeleid",
        "lead": "Kort en duidelijk: we gebruiken je gegevens enkel om je te helpen en te antwoorden.",
        "sections": [
            ("Wie is verantwoordelijk?", "Rozmary Digital, handelsnaam van [[legal]] ([[address]], ondernemingsnummer [[kbo]]), is verantwoordelijk voor de verwerking van je persoonsgegevens. Vragen stel je via [[email]]."),
            ("Welke gegevens?", "Wat je zelf invult in een formulier of stuurt via WhatsApp of e-mail: je naam, bedrijf, e-mailadres, telefoonnummer, website, gemeente en je bericht."),
            ("Waarom?", "Om je vraag te beantwoorden, een Groeiscan of voorstel te maken en, als je klant wordt, om onze overeenkomst uit te voeren en te factureren."),
            ("Hoe lang?", "Aanvragen die geen opdracht worden, wissen we na 12 maanden. Klantgegevens bewaren we zolang de wet dat vraagt, bijvoorbeeld 10 jaar voor facturen."),
            ("Cookies", "Deze website gebruikt geen tracking- of advertentiecookies. Enkel wat strikt nodig is om de site te laten werken."),
            ("Met wie delen we?", "Enkel met wie we nodig hebben om te werken: onze hosting (Hostinger), onze e-mail en de partners die aan je project meewerken, zoals een fotograaf of drukker. Zij krijgen alleen wat nodig is voor hun taak. We verkopen je gegevens nooit."),
            ("Je rechten", "Je mag je gegevens altijd inkijken, laten verbeteren of laten wissen. Stuur een mail naar [[email]]. Ben je niet tevreden, dan kan je terecht bij de Gegevensbeschermingsautoriteit (gegevensbeschermingsautoriteit.be)."),
        ],
    },
    "thanks": {
        "title": "Bedankt | Rozmary Digital",
        "desc": "Bedankt voor je bericht aan Rozmary Digital. We antwoorden binnen één werkdag.",
        "h1": "Bedankt, we hebben je bericht",
        "lead": "We antwoorden binnen één werkdag. Dringend? Stuur ons meteen een WhatsApp.",
        "back": "Terug naar de homepage",
    },
    "404": {
        "title": "Pagina niet gevonden | Rozmary Digital",
        "h1": "Deze pagina bestaat niet (meer)",
        "lead": "Misschien vind je het hier:",
    },
}

# De vijf stappen van het groeimodel (home + werkwijze).
MODEL = [
    ("Visie", "Voor wie ben jij de beste keuze?", "We leggen je doelgroep, je aanbod en je prijzen vast. Zo weet iedereen waarom ze voor jou moeten kiezen.", ["starter", "brand"]),
    ("Vindbaar", "Word je gevonden waar je klanten zoeken?", "Google, je Google-profiel, advertenties en social media: we zorgen dat je zichtbaar bent op het moment dat iemand zoekt.", ["google", "ads", "social"]),
    ("Vertrouwen", "Waarom kiezen ze voor jou?", "Een site, reviews, echte foto's en voorbeelden die tonen waarom ze voor jou kiezen en niet voor de buurman.", ["website", "photo", "cards"]),
    ("Verkoop", "Wordt een bezoeker een klant?", "WhatsApp, offerte, afspraak of online betalen, met automatische opvolging. Geen aanvraag die nog verloren gaat.", ["shop", "chatbot", "pos"]),
    ("Vasthouden", "Komt de klant terug en brengt hij anderen mee?", "Reviews vragen, een nieuwsbrief en onderhoud. Een vaste klant is goedkoper dan een nieuwe.", ["software", "social"]),
]
